URL     = https://github.com/jerryscript-project/jerryscript.git
METHOD  = git
VERSION = 678fcb20ed1355f7e55216ef8092bfaa07ed1a96
CMAKE_OPTS = -DJERRY_LIBC=OFF -DENABLE_LTO=OFF

include $(ROOTDIR)/tools/cmake.inc
