#!/bin/sh
#
# Action for Connect IT 4 LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

case "$1" in
start)
	ledcmd -a -N COM -N ETH -N ONLINE
	exit 0
	;;
reload)
	;;
stop)
	# Firmware flash
	ledcmd -a -n COM -n ETH -n ONLINE -o COM -f ETH -O ONLINE
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################

# Find the PRIMARY modem, or alternatively *any* modem
idx="$(modem name=modem idx 2> /dev/null)" || idx="$(modem idx 2> /dev/null)"
# Find the first interface on the modem
for i in $(runt keys mm.map.interface_idx); do
	[ "$(runt get mm.map.interface_idx.$i)" = "$idx" ] \
		&& intf=$i && break
done

if [ "$(runt get network.interface.$intf.ipv4.up)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.up)" = 1 ]; then
	if [ "$(runt get netmon.ipv4_interface_$intf.passed)" = n \
			-o "$(runt get netmon.ipv6_interface_$intf.passed)" = n ]; then
		CELL=1
	elif [ "$(runt get mm.modem.$idx.status.gtech)" = 4g ]; then
		CELL=3
	else
		CELL=2
	fi
elif [ "$(runt get network.interface.$intf.ipv4.pending)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.pending)" = 1 ]; then
	CELL=1
else
	CELL=0 # not-valid, never going to work
fi

if [ "$CELL" != 0 ]; then
	case "$(runt get mm.modem.$idx.status.bars)" in
	5) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -o RSS5" ;;
	4) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -O RSS5" ;;
	3) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -O RSS4 -O RSS5" ;;
	2) SIGNAL="-o RSS1 -o RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	1) SIGNAL="-o RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	*) SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	esac
else
	SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5"
fi

##############################################################

LINK=$(ip link show lan 2> /dev/null | grep -c "state UP")

LAN4=-1
LAN6=-1
if [ "$LINK" = 1 ]; then
	case $(runt get network.interface.lan.ipv4.up) in
	1) [ "$(runt get netmon.ipv4_interface_lan.passed)" = n ] && LAN4=1 || LAN4=2 ;;
	0) [ "$(runt get network.interface.lan.ipv4.pending)" = 1 ] && LAN4=1 || LAN4=0 ;;
	esac

	case $(runt get network.interface.lan.ipv6.up) in
	1) [ "$(runt get netmon.ipv6_interface_lan.passed)" = n ] && LAN6=1 || LAN6=2 ;;
	0) [ "$(runt get network.interface.lan.ipv6.pending)" = 1 ] && LAN6=1 || LAN6=0 ;;
	esac
fi

if [ "$LAN4" = -1 -a "$LAN6" = -1 ]; then
	# if neither interface exists, match link
	LAN=$((LINK ? 2 : 0))
elif [ "$LAN4" = 2 -o "$LAN6" = 2 ]; then
	LAN=2
elif [ "$LAN4" = 1 -o "$LAN6" = 1 ]; then
	LAN=1
else
	LAN=0
fi

##############################################################

PRIMARY="LAN3_RX"
BACKUP="LAN3_TX"

# work out if WAN is really our primary interface (WAN_LED LED) or not
wan4_metric="$(config get network.interface.wan.ipv4.metric)"
cell4_metric="$(config get modem.ipv4.metric)"

if [ ${cell4_metric} -lt ${wan4_metric} ]; then
	PRIMARY="LAN3_TX"
	BACKUP="LAN3_RX"
fi

LINK=$(ip link show wan 2> /dev/null | grep -c "state UP")
WAN4=-1
WAN6=-1
if [ "$LINK" = 1 ]; then
	case $(runt get network.interface.wan.ipv4.up) in
	1) [ "$(runt get netmon.ipv4_interface_wan.passed)" = n ] && WAN4=1 || WAN4=2 ;;
	0) [ "$(runt get network.interface.wan.ipv4.pending)" = 1 ] && WAN4=1 || WAN4=0 ;;
	esac

	case $(runt get network.interface.wan.ipv6.up) in
	1) [ "$(runt get netmon.ipv6_interface_wan.passed)" = n ] && WAN6=1 || WAN6=2 ;;
	0) [ "$(runt get network.interface.wan.ipv6.pending)" = 1 ] && WAN6=1 || WAN6=0 ;;
	esac
fi

# working out WAN state irrespective of which interface is PRIMARY
if [ "$WAN4" = -1 -a "$WAN6" = -1 ]; then
	WAN=$((LINK ? 2 : 0))
elif [ "$WAN4" = 2 -o "$WAN6" = 2 ]; then
	WAN=2
elif [ "$WAN4" = 1 -o "$WAN6" = 1 ]; then
	WAN=1
else
	WAN=0
fi

case "$WAN" in
2) WAN_LED="-o $PRIMARY" ;;
1) WAN_LED="-f $PRIMARY" ;;
*) WAN_LED="-O $PRIMARY" ;;
esac

case "$CELL" in
2|3) CELL_LED="-o $BACKUP" ;;
1) CELL_LED="-f $BACKUP" ;;
*) CELL_LED="-O $BACKUP" ;;
esac

##############################################################

#
# The LED table of things based on all possible values above
#
LED00="-f COM -O ONLINE -f ETH" # flashing yellow
LED10="-f COM -O ONLINE -f ETH" # flashing yellow
LED20="-O COM -O ONLINE -f ETH" # flashing green
LED30="-O COM -f ONLINE -O ETH" # flashing blue
LED01="-f COM -O ONLINE -f ETH" # flashing yellow
LED11="-f COM -O ONLINE -f ETH" # flashing yellow
LED21="-O COM -O ONLINE -f ETH" # flashing green
LED31="-O COM -f ONLINE -O ETH" # flashing blue
LED02="-f COM -f ONLINE -f ETH" # flashing white
LED12="-f COM -f ONLINE -f ETH" # flashing white
LED22="-O COM -O ONLINE -o ETH" # solid green
LED32="-O COM -o ONLINE -O ETH" # solid blue

eval ledcmd $SIGNAL $WAN_LED $CELL_LED \$LED$CELL$LAN

exit 0
