#!/bin/sh
#
# Action for ACM7004-5 LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

case "$1" in
start)
	ledcmd -a -N COM -N ETH -N ONLINE
	exit 0
	;;
reload)
	;;
stop)
	# Firmware flash
	ledcmd -a -n COM -n ETH -n ONLINE -o COM -f ETH -O ONLINE
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################

exit 0
