URL = https://github.com/radvd-project/radvd/releases/download/v2.19/radvd-2.19.tar.xz

ifdef CONFIG_USER_FLATFSD_ETC_CONFIG
CONFOPTS += --sysconfdir=/etc/config
endif

include $(ROOTDIR)/tools/automake.inc
