#!/bin/sh
[ "$IP_UP_RECURSED" ] && exit 0

IP_UP_RECURSED=1
export IP_UP_RECURSED

[ "$6" -a -x "/etc/ppp/$6-up" ] && exec "/etc/ppp/$6-up"
[ "$6" -a -x "/etc/config/$6-up" ] && exec "/etc/config/$6-up"

[ -x /etc/config/ip-up ] && exec /etc/config/ip-up "$@"

exit 0
