
URL = https://s3.amazonaws.com/json-c_releases/releases/json-c-0.11.tar.gz
CONFVARS = ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes
MAKEVARS = 

include $(ROOTDIR)/tools/automake.inc

