#
# Makefile -- Build instructions for Digi/TX64-Rail-Single-Cellular
#

include ../TX64-Rail-Single-Cellular-PR/tx64_rail_common.mak

romfs: romfs.tx64_rail_common
	echo "Digi TX64-Rail-Single-Cellular" > $(ROMFSDIR)/etc/issue
