
URL = http://pagesperso-orange.fr/sebastien.godard/sysstat-10.0.3.tar.bz2
CONFOPTS = --disable-man-group --disable-sensors  --disable-documentation
MAKEVARS = LFLAGS=-lintl

include $(ROOTDIR)/tools/automake.inc

