#
# Makefile -- Build instructions for Digi/TX64-Rail-Single-Cellular-PR
#

include tx64_rail_common.mak

romfs: romfs.tx64_rail_common
	echo "Digi TX64-Rail-Single-Cellular-PR" > $(ROMFSDIR)/etc/issue
