VERSION = 1.7.0
URL = https://github.com/kravietz/pam_tacplus/releases/download/v$(VERSION)/pam_tacplus-$(VERSION).tar.gz

CONFVARS += gl_cv_func_getopt_gnu=yes

include $(ROOTDIR)/tools/automake.inc
