VERSION    = 2.3.3
URL        = https://ftp.gnu.org/gnu/libidn/libidn2-$(VERSION).tar.gz
# CONFVARS   += LIBS=-lintl
# CONFVARS   += gl_cv_func_getopt_gnu=yes
# CONFVARS   += am_cv_func_working_getline=yes
MAKEVARS   = 
include $(ROOTDIR)/tools/automake.inc

