URL        = https://ftp.gnu.org/gnu/libidn/libidn2-2.1.1a.tar.gz
BUILDDIR   = libidn2-2.1.1
# CONFVARS   += LIBS=-lintl
# CONFVARS   += gl_cv_func_getopt_gnu=yes
# CONFVARS   += am_cv_func_working_getline=yes
MAKEVARS   = 
include $(ROOTDIR)/tools/automake.inc

