
URL = http://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-11.3.0.tar.gz
CONFOPTS += --disable-xmldoc
CONFVARS = ac_cv_search_res_9_ninit=no

include $(ROOTDIR)/tools/automake.inc

