URL = https://www.netfilter.org/projects/nftables/files/nftables-1.0.9.tar.xz
CFLAGS = -D_GNU_SOURCE
CONFOPTS += --disable-man-doc
CONFOPTS += --without-cli
MAKEVARS = 

include $(ROOTDIR)/tools/automake.inc
