
URL = https://download.rsyslog.com/libfastjson/libfastjson-0.99.9.tar.gz
DOWNLOADHASH = a330e1bdef3096b7ead53b4bad1a6158f19ba9c9ec7c36eda57de7729d84aaee

LIBTOOL = $(abspath $(shell pwd)/build/$(PKG)/libtool)
$(PKG)_CONFVARS = LIBS="-lm"

include $(ROOTDIR)/tools/automake.inc
