#!/bin/sh
#
# Action for CM71xx LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

POWERLED=/sys/class/leds/cm7100:green:power
HBLED=/sys/class/leds/cm7100:green:heartbeat
SERIALLED=/sys/class/leds/cm7100:green:serial
NETLED=/sys/class/leds/cm7100:green:network

case "$1" in
start)
	echo none > $POWERLED/trigger
	echo 255 > $POWERLED/brightness
	echo heartbeat > $HBLED/trigger
	echo netdev > $NETLED/trigger
	echo none > $SERIALLED/trigger
	echo 0 > $SERIALLED/brightness
	exit 0
	;;
reload)
	;;
stop)
	# Firmware flash
	for LED in $POWERLED $HBLED $SERIALLED $NETLED ; do
		echo timer > $LED/trigger
	done
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################

exit 0
