URL      = https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
METHOD   = git
VERSION  = 1.30.0

CONFOPTS += -Dbash_completion=false
CONFOPTS += -Dintrospection=false
CONFOPTS += -Dman=false

libmbim_ROMFS = libmbim_romfs

include $(ROOTDIR)/tools/meson.inc

libmbim_romfs:
