#!/bin/sh

if [ -f "/etc/config/scripts/alert-sms" ]; then
	exec "/etc/config/scripts/alert-sms" $@
fi

# Create the SMS file in spool
echo -e "To: $NUMBER\n\n$MSG" > /var/spool/sms/outgoing/sms-alert-$RANDOM

