#!/bin/sh

. /etc/scripts/snmp-env

#DEBUG=1
if [ "$DEBUG" == "1" ]; then
	FILE=/tmp/custom-alert
	DATE=`date`
	echo "$DATE" > $FILE
	echo "1:$1" >> $FILE
	echo "2:$2" >> $FILE
	echo "3:$3" >> $FILE
	echo "4:$4" >> $FILE
	echo "5:$5" >> $FILE
	echo "6:$6" >> $FILE
	echo "7:$7" >> $FILE
	echo "8:$8" >> $FILE
fi

legacy=`config -g config.system.snmp.legacytraps`
if [ ! -z "$legacy" ]; then
	exit
fi

retval=0
ACTION=$1

if [ "$ACTION" == "snmp" ]; then

	CustomNotification=33
	customCheckFailure=255

	export AGENT=""
	export UPTIME=""
	export NOTIFICATION="CustomNotification"
	export TRAP=$CustomNotification

	ALERT_CHECK=$2
	ALERT_REF=$3
	ALERT_TIME=$4
	ALERT_STATE=$5
	ALERT_SCRIPT=$6
	ALERT_RETURN=$7
	ALERT_TRIGGER=$8

	ALERT_TYPE=$customCheckFailure
	ALERT_VALUE=$ALERT_RETURN
	ALERT_DEVICE=$ALERT_SCRIPT

	TRIGGERED=2

	ESC_ALERT_SCRIPT=`echo "$ALERT_SCRIPT" | sed -e 's=/=\/=g'`

	if [ "$ALERT_STATE" == "$TRIGGERED" ]; then
		ALERT_SUMMARY="Custom script '$ESC_ALERT_SCRIPT' failed with value $ALERT_RETURN, expected $ALERT_TRIGGER"
	else
		ALERT_SUMMARY="Custom script '$ESC_ALERT_SCRIPT' passed with value $ALERT_RETURN as expected"
	fi

	/bin/sh /etc/scripts/alert-snmp \
		"AlarmType" \
		"i" \
		"$ALERT_TYPE" \
		"AlarmCheck" \
		"i" \
		"$ALERT_CHECK" \
		"AlarmInstance" \
		"i" \
		"$ALERT_REF" \
		"AlarmTime" \
		"x" \
		"$ALERT_TIME" \
		"AlarmState" \
		"i" \
		"$ALERT_STATE" \
		"AlarmSummary" \
		"s" \
		"$ALERT_SUMMARY" \
		"AlarmDevice" \
		"s" \
		"$ALERT_DEVICE" \
		"AlarmCurrentValue" \
		"i" \
		"$ALERT_VALUE" \
		"AlarmTriggerValue" \
		"i" \
		"$ALERT_TRIGGER"

	retval=$(( $? || $retval ))
fi

exit $retval
