#!/bin/sh                                                                       
                                                                                
# If there's a user-configured script, run it instead                           
script=$(basename $0)                                                           
if [ -f "/etc/config/scripts/$script" ]; then
	exec "/etc/config/scripts/$script" $@                                   
fi
