#!/bin/bash

MODEM=$6

# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/dialout-up.${MODEM}"
scripts[1]="/etc/config/scripts/dialout-up"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
        if [ -f "${scripts[$i]}" ]; then
                exec /bin/sh "${scripts[$i]}" "$@"
        fi
done

ln -sf /var/run/${IFNAME}.resolv /var/run/ppp-${MODEM}.resolv
# Push our resolv.conf into resolvconf 
if [ -f /etc/config/network/dialout.${MODEM}.resolv ]; then
	RESOLV=/etc/config/network/dialout.${MODEM}.resolv
else
	RESOLV=/var/run/${IFNAME}.resolv
fi

# Clear out existing cellmodem entries, just in case PPP died before 
# running the dialout-down script
/bin/resolvconf -d ${MODEM}
cat $RESOLV | /bin/resolvconf -a ${MODEM}

sh /etc/ifup

if [ -x /bin/devlog ]; then
	/bin/devlog -i ${IFNAME} -p /var/run/devlog.${IFNAME}.pid --background
fi

# record dial info into infod
/etc/scripts/dial-info "connected"

# Clear retry count on successful connection
rm -f /var/run/.modem/retry_count
