#!/bin/bash

MODEM=$6

# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/dialout-down.${MODEM}"
scripts[1]="/etc/config/scripts/dialout-down"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
        if [ -f "${scripts[$i]}" ]; then
                exec /bin/sh "${scripts[$i]}" "$@"
        fi
done

# Push our resolv.conf into resolvconf 
/bin/resolvconf -d ${MODEM}

if [ -f /var/run/devlog.${IFNAME}.pid ]; then
	kill -TERM `cat /var/run/devlog.${IFNAME}.pid`
fi

# record dial info into infod
/etc/scripts/dial-info "disconnected"

