#!/bin/sh

. /etc/scripts/snmp-env

#DEBUG=1
if [ "$DEBUG" == "1" ]; then
	FILE=/tmp/environmental-alert
	DATE=`date`
	echo "$DATE" > $FILE
	echo "1:$1" >> $FILE
	echo "2:$2" >> $FILE
	echo "3:$3" >> $FILE
	echo "4:$4" >> $FILE
	echo "5:$5" >> $FILE
	echo "6:$6" >> $FILE
	echo "7:$7" >> $FILE
	echo "8:$8" >> $FILE
	echo "9:$9" >> $FILE
	echo "10:${10}" >> $FILE
	echo "11:${11}" >> $FILE
fi

legacy=`config -g config.system.snmp.legacytraps`
if [ ! -z "$legacy" ]; then
	. /etc/scripts/environmental-alertv1 "$1" "$6" "$7" "$8" "$9"
	exit
fi

ACTION=$1
retval=0
if [ "$ACTION" == "snmp" ]; then

	export AGENT=""
	export UPTIME=""

	EmdTemperatureNotification=8
	EmdHumidityNotification=9

	unknown=65535
	envTemperatureHigh=14
	envTemperatureLow=13
	envHumidityHigh=16
	envHumidityLow=15

	ALERT_CHECK=$2
	ALERT_REF=$3
	ALERT_TIME=$4
	ALERT_STATE=$5
	ALERT_DEVICE=$6
	ALERT_DEVICE_TYPE=$7
	ALERT_SENSOR=$8
	ALERT_VALUE=$9
	ALERT_TRIGGER_VALUE=${10}
	ALERT_COMPARE=${11}
	ALERT_OLD_VALUE=-1
	ALERT_SUMMARY=""
	ALERT_TYPE=$unknown
	ALERT_USER=$ALERT_DEVICE_TYPE

	RESOLVED=1
	TRIGGERED=2
	UNRESOLVABLE=3

	if [ "$ALERT_SENSOR" == "temp" ]; then
		export NOTIFICATION="EmdTemperatureNotification"
		export TRAP=$EmdTemperatureNotification
		if [ "$ALERT_COMPARE" == "lesser" ]; then
			ALERT_TYPE=$envTemperatureLow
		else
			ALERT_TYPE=$envTemperatureHigh
		fi
		ALERT_SUMMARY="EMD '$ALERT_DEVICE' temperature is now $ALERT_VALUE degrees, trigger was $ALERT_TRIGGER_VALUE degrees"
	elif [ "$ALERT_SENSOR" == "humid" ]; then
		export NOTIFICATION="EmdHumidityNotification"
		export TRAP=$EmdHumidityNotification
		if [ "$ALERT_COMPARE" == "lesser" ]; then
			ALERT_TYPE=$envHumidityLow
		else
			ALERT_TYPE=$envHumidityHigh
		fi
		ALERT_SUMMARY="EMD '$ALERT_DEVICE' humidity is now $ALERT_VALUE%, trigger was $ALERT_TRIGGER_VALUE%"
	else
		echo "Unsupported alert type: $ALERT_SENSOR"
		exit 1
	fi

	if [ "$ALERT_STATE" == "-1" ]; then
		ALERT_STATE=$UNRESOLVABLE
	fi

	/bin/sh /etc/scripts/alert-snmp \
		"AlarmType" \
		"i" \
		"$ALERT_TYPE" \
		"AlarmCheck" \
		"i" \
		"$ALERT_CHECK" \
		"AlarmInstance" \
		"i" \
		"$ALERT_REF" \
		"AlarmTime" \
		"x" \
		"$ALERT_TIME" \
		"AlarmState" \
		"i" \
		"$ALERT_STATE" \
		"AlarmDevice" \
		"s" \
		"$ALERT_DEVICE" \
		"AlarmUser" \
		"s" \
		"$ALERT_USER" \
		"AlarmTriggerValue" \
		"i" \
		"$ALERT_TRIGGER_VALUE" \
		"AlarmCurrentValue" \
		"i" \
		"$ALERT_VALUE" \
		"AlarmPreviousValue" \
		"i" \
		"$ALERT_OLD_VALUE" \
		"AlarmSummary" \
		"s" \
		"$ALERT_SUMMARY"

	retval=$(( $? || $retval ))
fi
