#!/bin/bash

# Read SNMP configuration
while read -r line
do
	key=`echo "$line" | cut -f4 -d. | cut -f1 -d' '`
	val=`echo "$line" | cut -f2 -d' '`
	declare ${key}=${val}
done < <(config -g config.system.snmp)

# If we are configured as SNMPv3 with no explicit Engine-ID,
# send a v3 trap to localhost to force generation of snmpapp.conf
for suffix in "" "2"
do
	v="version${suffix}"
	e="engine${suffix}"
	s="seclevel${suffix}"
	u="username${suffix}"
	a="authprotocol${suffix}"
	A="authpassword${suffix}"
	x="privprotocol${suffix}"
	X="privpassword${suffix}"

	if [ "${!v}" = "3" -a -z "${!e}" -a ! -z "${!s}" ]; then
		cmd="/bin/snmptrap -v 3 -l ${!s} -u \"${!u}\""
		if [ "${!s}" = "authNoPriv" -o "${!s}" = "authPriv" ]; then
			cmd="${cmd} -a ${!a} -A \"${!A}\""
		fi
		if [ "${!seclevel}" = "authPriv" ]; then
			cmd="${cmd} -x ${!x} -X \"${!X}\""
		fi
		cmd="${cmd} 127.0.0.1 42 warmStart.0"

		logger "Generating /var/run/snmpd/snmpapp.conf"
		${cmd}
	fi
done

