#!/bin/sh

if [ -f "/etc/config/scripts/modem-cmd" ]; then
	exec "/etc/config/scripts/modem-cmd" "$@"
fi

# Response to wait for
DEFAULT_RESPONSE="OK"

# Timeout in seconds
DEFAULT_TIMEOUT=2

logat()
{
	command="$1"
	response="$2"
	timeout="$3"

	if [ -x /bin/mmcli ] ; then
		mmpath=`mmcli -L | grep ModemManager1 | awk '{print $1}'`
		if [ -n "$mmpath" ]; then
			output=$(mmcli -m "$mmpath" --command="$command")
			if [ -n "$output" ] && [ "$output" != *"error"* ]; then
				echo "$output"
				exit 0
			fi
		fi
	fi

	# Fall back on direct read/write the AT port
	if [ -e /dev/cellcommand01 ] ; then
		output=$( ( COMMAND="$command" RESPONSE="$response" \
			/bin/chat -t $timeout -E -V -f /etc/scripts/command-chat \
			< /dev/cellcommand01 > /dev/cellcommand01 ) 2>&1 )
		echo "$output" | grep -v '^$'
		exit 0
	fi

	exit 1
}

if [ "$#" == "0" -o "$#" -gt 3 ]; then
	echo "usage: $0 'AT-COMMAND' [RESPONSE] [TIMEOUT]"
	echo " Hint: Use single quotes around AT command."
	echo " Defalt RESPONSE is OK, default TIMEOUT is 2"
	exit 1
fi

if [ "$#" -eq "3" ]; then
	command="$1"
	response="$2"
	timeout=$3
elif [ "$#" -eq "2" ]; then
	command="$1"
	response=$2
	timeout="$DEFAULT_TIMEOUT"
else
	command="$1"
	response="$DEFAULT_RESPONSE"
	timeout="$DEFAULT_TIMEOUT"
fi

logat ${command} ${response} ${timeout}
