#!/bin/sh

# If there's a user-configured script, run it instead
script="/etc/config/scripts/$(basename $0)"
if [ -f "$script" ]; then
	exec /bin/sh "$script" $@
fi

if [ -z "$1" ]; then
	echo "Usage: $(basename $0) upsname@server|all"
fi

if [ "$1" == "all" ]; then
	# Shutdown all UPSes
	upsmon -c fsd && upsdrvctl shutdown
	# We may not have lost power, try respawning upsmon
	sleep 60 && upsmon -p
else
	upsname=$(echo "$1" | cut -f1 -d'@')
	server=$(echo "$1" | cut -f2 -d'@')

	if [ "$server" == '[localhost]' -o "$server" == 'localhost' ]; then
		# Shutdown local UPS
		upsmon -S "$upsname" && upsdrvctl shutdown "$upsname"
	fi
fi

exit $?
