#!/bin/sh

# If there's a user-configured script, run it instead
script="/etc/config/scripts/$(basename $0)"
if [ -f "$script" ]; then
	exec /bin/sh "$script" "$@"
fi

upsname=$(echo "$1" | cut -f1 -d'@')
server=$(echo "$1" | cut -f2 -d'@')
