#! /bin/sh

/bin/sh /etc/scripts/ups-notify "$UPSNAME" "$NOTIFYTYPE"

case $1 in
	shutdown)
		/bin/sh /etc/scripts/ups-shutdown "$UPSNAME"
		;;
	shutdown-all)
		/bin/sh /etc/scripts/ups-shutdown all
		;;
	clear-shutdown)
		upsmon -U $(echo "$UPSNAME" | cut -f1 -d'@')
		;;
	*)
		;;
esac

