#!/bin/sh

. /etc/scripts/snmp-env

# DEBUG=1
if [ "$DEBUG" == "1" ]; then
	FILE=/tmp/webui-user-alert
	DATE=`date`
	echo "$DATE" > $FILE
	echo "1:$1" >> $FILE
	echo "2:$2" >> $FILE
	echo "3:$3" >> $FILE
	echo "4:$4" >> $FILE
	echo "5:$5" >> $FILE
	echo "6:$6" >> $FILE
	echo "7:$7" >> $FILE
	echo "8:$8" >> $FILE
	echo "9:$9" >> $FILE
fi

legacy=`config -g config.system.snmp.legacytraps`
if [ ! -z "$legacy" ]; then
	exit
fi

retval=0
ACTION=$1

if [ "$ACTION" == "snmp" ]; then

	WebUserNotification=7
	webUserSession=12

	export AGENT=""
	export UPTIME=""
	export NOTIFICATION="WebUserNotification"
	export TRAP=$WebUserNotification

	ALERT_CHECK=$2
	ALERT_REF=$3
	ALERT_TIME=$4
	ALERT_STATE=$5
	USER_EVENT=$6
	ALERT_USER=$7
	ALERT_ADDRESS=$8
	ALERT_PORT=$9
	ALERT_DEVICE="$ALERT_ADDRESS:$ALERT_PORT"

	ALERT_TYPE=$webUserSession

	ALERT_TRIGGER_VALUE=-1

	if [ "$USER_EVENT" == "LOGIN" ]; then
		ALERT_SUMMARY="User '$ALERT_USER' logged in to the Management Console from $ALERT_DEVICE"
		ALERT_VALUE=1
		ALERT_OLD_VALUE=0
	elif [ "$USER_EVENT" == "LOGOUT" ]; then
		ALERT_SUMMARY="User '$ALERT_USER' logged out of the Management Console from $ALERT_DEVICE"
		ALERT_VALUE=0
		ALERT_OLD_VALUE=1
	elif [ "$USER_EVENT" == "AUTH ERROR" ]; then
		ALERT_SUMMARY="User '$ALERT_USER' attempted to login to the Management Console from $ALERT_DEVICE"
		ALERT_VALUE=0
		ALERT_OLD_VALUE=1
	else
		echo "Unknown web user action: $USER_EVENT"
		exit 1
	fi

	/bin/sh /etc/scripts/alert-snmp \
		"AlarmType" \
		"i" \
		"$ALERT_TYPE" \
		"AlarmCheck" \
		"i" \
		"$ALERT_CHECK" \
		"AlarmInstance" \
		"i" \
		"$ALERT_REF" \
		"AlarmTime" \
		"x" \
		"$ALERT_TIME" \
		"AlarmState" \
		"i" \
		"$ALERT_STATE" \
		"AlarmDevice" \
		"s" \
		"$ALERT_DEVICE" \
		"AlarmUser" \
		"s" \
		"$ALERT_USER" \
		"AlarmSummary" \
		"s" \
		"$ALERT_SUMMARY" \
		"AlarmTriggerValue" \
		"i" \
		"$ALERT_TRIGGER_VALUE" \
		"AlarmCurrentValue" \
		"i" \
		"$ALERT_VALUE" \
		"AlarmPreviousValue" \
		"i" \
		"$ALERT_OLD_VALUE"

	retval=$(( $? || $retval ))
fi

exit $retval
