#!/bin/sh

#
# serial-mode.sh - setup and control serial port interface mode
#
# (C) Copyright 2020, Digi International.
#

#
# GPIO376 = port 1 termination/biasing (output, active high, default low)
# GPIO377 = port 2 termination/biasing (output, active high, default low)
# GPIO378 = port 3 termination/biasing (output, active high, default low)
# GPIO379 = port 4 termination/biasing (output, active high, default low)
# GPIO380 = port 5 termination/biasing (output, active high, default low)
# GPIO381 = port 6 termination/biasing (output, active high, default low)
# GPIO382 = port 7 termination/biasing (output, active high, default low)
# GPIO383 = port 8 termination/biasing (output, active high, default low)
# GPIO368 = port 1 2-wire, half-duplex enable (output, active high, default low)
# GPIO369 = port 2 2-wire, half-duplex enable (output, active high, default low)
# GPIO370 = port 3 2-wire, half-duplex enable (output, active high, default low)
# GPIO371 = port 4 2-wire, half-duplex enable (output, active high, default low)
# GPIO372 = port 5 2-wire, half-duplex enable (output, active high, default low)
# GPIO373 = port 6 2-wire, half-duplex enable (output, active high, default low)
# GPIO374 = port 7 2-wire, half-duplex enable (output, active high, default low)
# GPIO375 = port 8 2-wire, half-duplex enable (output, active high, default low)
#

serial_init() {
	# The initialization prepares GPIOs, but defers mode shift
	# until mode is selected.
	term="$((376 + $1))"
	wire="$((368 + $1))"
	echo "${term}" > /sys/class/gpio/export
	echo "${wire}" > /sys/class/gpio/export
}

serial_rs232() {
	wire="$((368 + $1))"
	echo "low" > /sys/class/gpio/gpio${wire}/direction
	echo "$1,232" > /sys/class/tty/ttyS2/device/uart_mode
}

serial_rs422() {
	wire="$((368 + $1))"
	echo "low" > /sys/class/gpio/gpio${wire}/direction
	echo "$1,422" > /sys/class/tty/ttyS2/device/uart_mode
}

serial_rs485() {  # 2-wire, half-duplex
	wire="$((368 + $1))"
	echo "high" > /sys/class/gpio/gpio${wire}/direction
	echo "$1,485_2W" > /sys/class/tty/ttyS2/device/uart_mode
}

serial_nonterminate() {
	term="$((376 + $1))"
	echo "low" > /sys/class/gpio/gpio${term}/direction
}

serial_terminate() {
	term="$((376 + $1))"
	echo "high" > /sys/class/gpio/gpio${term}/direction
}

usage() {
	echo "usage: serial-mode <device> (init|rs-232|rs-422|rs-485) [terminate]"
	echo
	echo "        init      -- initialize port control"
	echo "        powerdown -- not supported"
	echo "        rs-232    -- set port into RS-232 mode (default)"
	echo "        rs-422    -- set port into RS-422 mode"
	echo "        rs-485    -- set port into RS-485 mode"
	echo "        terminate -- enable line termination"
	echo
	exit 1
}

#
# Check arguments, and error out on anything invalid.
#
if [ $# -lt 2 -o $# -gt 3 ] ; then
	usage
fi

portnum="${1#/dev/serial/port}"
if [ "${portnum}" -lt "1" ] || [ "${portnum}" -gt "8" ] ; then
	echo "ERROR: serial-mode not supported on supplied port"
	exit 1
fi

portnum=$((${portnum} - 1))

case "$2" in
init)	serial_init ${portnum} ;;
powerdown)
	# Not supported, exit with success
	exit 0
	;;
rs-232)	serial_rs232 ${portnum} ;;
rs-422)	serial_rs422 ${portnum} ;;
rs-485)	serial_rs485 ${portnum} ;;
*)	usage ;;
esac

if [ "$3" = "terminate" ] && [ "$2" != "rs-232" ] ; then
	serial_terminate ${portnum}
else
	serial_nonterminate ${portnum}
fi

exit 0
