URL = https://dianne.skoll.ca/projects/rp-pppoe/download/rp-pppoe-3.12.tar.gz

BUILDDIR = ./rp-pppoe-3.12/src
CONFVARS += c_cv_linux_kernel_pppoe=yes
CONFVARS += rpppoe_cv_pack_bitfields=normal
CONFVARS += PPPD=/bin/pppd

include $(ROOTDIR)/tools/automake.inc
