VERSION = 3.18
URL = https://github.com/axboe/fio/archive/fio-$(VERSION).tar.gz

BUILDDIR=fio-fio-$(VERSION)
include $(ROOTDIR)/tools/automake.inc

CONFIGURE_OPTS=
CONFOPTS = --disable-native --prefix=$(PREFIX)

