CONFOPTS += --without-stackprotect
CONFVARS = gl_cv_warn_c__fstack_protector__Werror=no
MAKEVARS = 
URL = http://blinkenlights.nl/software/ladvd/ladvd-1.1.1.tar.gz
include $(ROOTDIR)/tools/automake.inc
