BASEVER = 2.11
VERSION = $(BASEVER).4

URL      := https://download.gnome.org/sources/libxml2/$(BASEVER)/libxml2-$(VERSION).tar.xz
CONFOPTS := --without-python
MAKEVARS =

include $(ROOTDIR)/tools/automake.inc

