URL      = https://github.com/philipc/tinyrl.git
VERSION  = b5471fe6e8aa81355ae5552a8f6254ba092eaec7
METHOD   = git

ifdef CONFIG_LIB_TINYRL_DISABLE_BELL
CMAKE_OPTS += -DDISABLE_BELL=ON
endif

include $(ROOTDIR)/tools/cmake.inc
