URL = https://web.mit.edu/kerberos/dist/krb5/1.18/krb5-1.18.tar.gz
BUILDDIR = krb5-1.18/src

CONFVARS += krb5_cv_attr_constructor_destructor=yes,yes
CONFVARS += ac_cv_func_regcomp=yes
CONFVARS += ac_cv_printf_positional=yes

include $(ROOTDIR)/tools/automake.inc
