VERSION = 2.21
URL = http://ftpmirror.gnu.org/gnu/units/units-$(VERSION).tar.gz

# Static currency exchange rates
CONFOPTS += --sharedstatedir=/etc
CONFVARS += ac_cv_path_PYTHON=no

include $(ROOTDIR)/tools/automake.inc

