URL      = https://git.openwrt.org/project/uci.git
VERSION  = f199b961c2970b63cc83947ad49b327b3f48f05f
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0
CFLAGS   += -DUCI_CONFDIR=\"/var/run/uci\"

include $(ROOTDIR)/tools/cmake.inc
