URL      = https://git.openwrt.org/project/uci.git
VERSION = f84f49f00fb70364f58b4cce72f1796a7190d370
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0
CFLAGS   += -DUCI_CONFDIR=\"/var/run/uci\"

include $(ROOTDIR)/tools/cmake.inc
