URL      = git://nbd.name/uci.git
VERSION  = 2549fb84542a6b59a1a21dfd7fc9fd51700c8ce3
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0
CFLAGS   += -DUCI_CONFDIR=\"/var/run/uci\"

include $(ROOTDIR)/tools/cmake.inc
