#!/bin/sh
#
# Do the minimum required to mount the rootfs and init.

mount -t proc proc proc

[ -b /dev/vda1 ] \
	&& DEV=/dev/vda1 || DEV=/dev/sda1

cat /proc/cmdline | grep -q 'bootpart=b' \
	&& IMAGE=image1 || IMAGE=image

echo "Loop boot loading $IMAGE from $DEV..."

e2fsck -p $DEV
mount -t ext4 $DEV /mnt/disk
mount -t squashfs -o loop /mnt/disk/$IMAGE /mnt/image

cd /mnt/image
pivot_root . ./boot/initrd

mount --move /boot/initrd/dev /dev
mount --move /boot/initrd/proc /proc
mount --move /boot/initrd/mnt/disk /mnt/disk

exec /usr/sbin/chroot . /bin/init

