#!/bin/sh
#
# mkffs -- make the disk filesystem for Porter
#
# Creates fdisk style partitions and installs GRUB.
#

# Device to setup and boot from
DEV=$1
if [ -z "$DEV" ]; then
	# /dev/sd* is SATA bus
	# /dev/vd* is virtio bus
	[ -b /dev/vda ] && DEV=/dev/vda || DEV=/dev/sda
fi

IMAGEDEV=$2
if [ -z "$IMAGEDEV" ]; then
	[ -b /dev/vdb ] && IMAGEDEV=/dev/vdb || IMAGEDEV=/dev/sdb
fi

# Need some of these to run grub-install
mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir -m 755 /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs -o size=256M tmpfs /tmp
mount -t tmpfs -o size=256M tmpfs /var
mkdir -m 1777 /var/tmp
mkdir -m 755 /var/log
mkdir -m 755 /var/run
mkdir -m 1777 /var/lock
mkdir -m 755 /var/empty
mkdir -m 755 /var/mnt

echo "======== Partitioning disk ========"

dd if=/dev/zero of=$DEV bs=512 count=1

# Must select a cylinder size just large enough for grub.
# Our grub primary boot is larger due to supporting squashfs, loopback, etc.
CYLSIZEK=256
DISKSIZEK=`sfdisk -s $DEV`
CYL=`expr $DISKSIZEK / $CYLSIZEK`

# Create one partition. Everything will go here.
sfdisk -f -q -C$CYL -H$CYLSIZEK -S2 -L $DEV << EOF
1,,L
EOF

echo "======== Formatting disk ========"

ROOTDIR=/var/mnt/root
mkdir $ROOTDIR

# Make filesystem. ext2 provides good metadata/data ratio.
mkfs.ext2 ${DEV}1
mount -t ext2 ${DEV}1 $ROOTDIR

mkdir $ROOTDIR/opt
mkdir $ROOTDIR/config
touch $ROOTDIR/config/.init

echo "======== Setting up bootloader ========"

mkdir -p $ROOTDIR/opt/boot
grub-editenv $ROOTDIR/opt/boot/grubenv create
grub-editenv $ROOTDIR/opt/boot/grubenv set default=0

/etc/grub-install $DEV

echo "======== Installing images ========"

dd if=$IMAGEDEV of=$ROOTDIR/image
dd if=$IMAGEDEV of=$ROOTDIR/image1

umount $ROOTDIR

exit 0
