VERSION  = 3.9.0
URL      = https://github.com/thom311/libnl/releases/download/libnl$(subst .,_,$(VERSION))/libnl-$(VERSION).tar.gz
CONFOPTS = --disable-cli
MAKEVARS =

include $(ROOTDIR)/tools/automake.inc
