ACL_LICENSE = Public Domain
URL = https://sourceforge.net/projects/expect/files/Expect/5.45.4/expect5.45.4.tar.gz

CONFOPTS += --with-tcl=$(ROOTDIR)/staging/lib
CONFOPTS += --with-tclinclude=$(ROOTDIR)/staging/include

include $(ROOTDIR)/tools/automake.inc

