#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y                       		:= ks8692_utils.o ks8692_mm.o

obj-$(CONFIG_MACH_ACM500X)		+= acm500x.o
obj-$(CONFIG_LEDS)			+= leds.o
obj-$(CONFIG_PCI)			+= ks8692_pci.o pci.o
obj-$(CONFIG_CPU_FREQ_INTEGRATOR)	+= cpu.o
