#!/bin/sh

update_resolv() {
	local device="$1"
	local dns="$2"
	(
		[ -n "$DOMAINS" ] && echo "search $DOMAINS"
		for i in $dns; do
			echo "nameserver $i"
		done
	) | /bin/resolvconf -a $device.dhcp6
}

setup_interface () {
	local device="$1"

	# Merge RA-DNS
	for radns in $RA_DNS; do
		local duplicate=0
		for dns in $RDNSS; do
			[ "$radns" = "$dns" ] && duplicate=1
		done
		[ "$duplicate" = 0 ] && RDNSS="$RDNSS $radns"
	done

	local dnspart=""
	for dns in $RDNSS; do
		if [ -z "$dnspart" ]; then
			dnspart="\"$dns\""
		else
			dnspart="$dnspart, \"$dns\""
		fi
	done

	update_resolv "$device" "$dns"
}

teardown_interface() {
	local device="$1"
	update_resolv "$device" ""
}

case "$2" in
	bound)
		teardown_interface "$1"
		setup_interface "$1"
	;;
	informed|updated|rebound|ra-updated)
		setup_interface "$1"
	;;
	stopped|unbound)
		teardown_interface "$1"
	;;
	started)
		teardown_interface "$1"
	;;
esac
