VERSION = 20230802.1
URL = https://github.com/abseil/abseil-cpp/archive/refs/tags/$(VERSION).tar.gz
BUILDDIR = abseil-cpp-$(VERSION)
CMAKE_OPTS += -DCMAKE_SYSTEM_NAME=$(TARGETARCH)
include $(ROOTDIR)/tools/cmake.inc