#!/bin/sh

#
# serial-mode.sh - setup and control serial port interface mode
#
# This control script is specific to the Digi/ConnectEZ1.
#
# (C) Copyright 2020, Digi International.
#

#
# GPIO444 = UART GPIO 4: differential termination enable (output, active high, default low)
# GPIO445 = UART GPIO 5: 2-wire, half-duplex enable (output, active high, default low)
# GPIO446 = UART GPIO 6: RX enable (output, active high, default high)
# GPIO447 = UART GPIO 7: RS232 (otherwise differential) (output, active high, default high)
#

serial_init() {
	# The initialization puts the port into RS-232 mode
	echo 444 > /sys/class/gpio/export
	echo low > /sys/class/gpio/gpio444/direction
	echo 445 > /sys/class/gpio/export
	echo low > /sys/class/gpio/gpio445/direction
	echo 446 > /sys/class/gpio/export
	echo high > /sys/class/gpio/gpio446/direction
	echo 447 > /sys/class/gpio/export
	echo high > /sys/class/gpio/gpio447/direction
}

serial_rs232() {
	echo 0 > /sys/class/gpio/gpio444/value
	echo 0 > /sys/class/gpio/gpio445/value
	echo 1 > /sys/class/gpio/gpio446/value
	echo 1 > /sys/class/gpio/gpio447/value
}

serial_rs422() {
	echo 0 > /sys/class/gpio/gpio444/value
	echo 0 > /sys/class/gpio/gpio445/value
	echo 1 > /sys/class/gpio/gpio446/value
	echo 0 > /sys/class/gpio/gpio447/value
}

serial_rs485() {  # 2-wire, half-duplex
	echo 0 > /sys/class/gpio/gpio444/value
	echo 1 > /sys/class/gpio/gpio445/value
	echo 1 > /sys/class/gpio/gpio446/value
	echo 0 > /sys/class/gpio/gpio447/value
}

serial_nonterminate() {
	echo 0 > /sys/class/gpio/gpio444/value
}

serial_terminate() {
	echo 1 > /sys/class/gpio/gpio444/value
}

usage() {
	echo "usage: serial-mode <device> (init|rs-232|rs-422|rs-485) [terminate]"
	echo
	echo "        init      -- initialize port control"
	echo "        rs-232    -- set port into RS-232 mode (default)"
	echo "        rs-422    -- set port into RS-422 mode"
	echo "        rs-485    -- set port into RS-485 mode"
	echo "        terminate -- enable line termination"
	echo
	exit 1
}

#
# Check arguments, and error out on anything invalid.
#
if [ $# -lt 2 -o $# -gt 3 ] ; then
	usage
fi
if [ "$1" != "/dev/serial/port1" ] ; then
	echo "ERROR: serial-mode only supported on /dev/serial/port1"
	exit 1
fi

case "$2" in
init)	serial_init ;;
rs-232)	serial_rs232 ;;
rs-422)	serial_rs422 ;;
rs-485)	serial_rs485 ;;
*)	usage ;;
esac

if [ "$3" = "terminate" ] ; then
	serial_terminate
else
	serial_nonterminate
fi

exit 0
