#!/bin/sh
#
# Action for AnywhereUSB 8/24 specific LED setting
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

wwan_led_update()
{
	WWAN_SERV=
	WWAN_SIG=

	idx="$(modem name=wwan idx || modem idx)" 2>/dev/null
	if [ -z "$idx" ]; then
		if sim -m 2>/dev/null | grep -qw yes; then
			# Slow flash SERV while waiting for modem to appear
			WWAN_SERV="-f wanserg"
			WWAN_SIG="-O wansigg -O wansigr"
		else
			# No modem present at all. Everything off
			WWAN_SERV="-O wanserg -O wanserr"
			WWAN_SIG="-O wansigg -O wansigr"
		fi
	else
		case "$(runt get mm.modem.$idx.status.bars)" in
		5)   WWAN_SIG="-o wansigg -O wansigr" ;;
		4|3) WWAN_SIG="-F wansigg -O wansigr" ;;
		2|1) WWAN_SIG="-f wansigg -O wansigr" ;;
		0)   WWAN_SIG="-O wansigg -f wansigr" ;;
		*)   WWAN_SIG="-O wansigg -O wansigr" ;;
		esac

		if [ "$(runt get mm.modem.$idx.status.state)" = connected ]; then
			WWAN_SERV="-o wanserg"
		elif [ -z "$(runt get mm.modem.$idx.modem.imsi)" ]; then
			# No SIM present
			WWAN_SERV="-o wanserr"
		else
			# Connecting
			WWAN_SERV="-F wanserg"
		fi
	fi
}

findme_update()
{
	FINDME=
	if find-me state &>/dev/null; then
		FINDME="-o usrg -F usrr"
	else
		FINDME="-O usrg -O usrr"
	fi
}

case "$1" in
start|stop)
	ledcmd -O usrg -O usrr
	ledcmd -O wansigg -O wansigr
	ledcmd -O wanserg -O wanserr
	;;
reload)
	findme_update
	wwan_led_update
	ledcmd $WWAN_SERV $WWAN_SIG $FINDME
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################
exit 0
