#!/bin/sh
#
# Action for CCMP13DK LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

# Note: We've assigned each of the LEDs the same label as what is on the
# silkscreen of the board (i.e. uled, user1, user2).
# Final products build on the CCMP1 SOMs will have more meaningful names.

# flash all three LEDs
findme_update() {
	FINDME=
	if find-me state &>/dev/null; then
		FINDME="-a -n uled -n user1 -n user2 -f uled -f user1 -f user2"
	else
		FINDME="-a -o uled -N user1 -N user2"
	fi
	ledcmd $FINDME
}

case "$1" in
start)
	ledcmd -o uled
	ledcmd -a -N user1 -N user2
	exit 0
	;;
reload)
	findme_update
	;;
stop)
	# Firmware flash
	ledcmd -a -n uled -n user1 -n user2 -o uled -f user1 -O user2
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

# Ethernet (LAN) status
##############################################################
if [ "$(runt get network.interface.eth.ipv4.up)" = 1 ]; then
	# Flash user1 if the interface is up
	LAN="-f user1"
else
	# Otherwise just keep it solid
	LAN="-o user1"
fi

# XBee LED
##############################################################
# When XBee is disabled, LED is off.
# When XBee is enabled:
#    Flashing green: XNM is running and we're online
#    Solid green: XNM is not running, or we're doing some management activity.
# Basic implementation here is copied from IX15/led.
if [ "$(config get xbee.enable)" = 0 ]; then
	XBEE_LED="-O user2"
elif [ -f "/var/run/xnm.pid" ] && /bin/sumo /bin/kill -0 $(/bin/admin-file cat /var/run/xnm.pid) >/dev/null 2>&1; then
	case "$(runt get xbee.xnm.status.code)" in
	# Online
	0)
		XBEE_LED="-f user2"
		;;
	# Offline
	1)
		XBEE_LED="-o user2"  # solid
		;;
	# 2 - Local update process in progress
	# 3 - Remote update process in progress
	# 4 - Recovery in progress
	# 5 - Network discovery in progress
	# 6 - Neighbor discovery in progress
	# 8 - Active discovery in progress
	*)
		XBEE_LED="-F user2"  # flash quickly
		;;
	esac
else
	XBEE_LED="-O user2"
fi

# Final LED command
##############################################################
ledcmd $LAN $XBEE_LED

exit 0

