
export ACL_LICENSE = GPL

URL = https://ftp.debian.org/debian/pool/main/m/mii-diag/mii-diag_2.11.orig.tar.gz
BUILDDIR = mii-diag-2.11.orig
MAKEVARS = CFLAGS="$(CFLAGS)" CC="$(CC)"

include $(ROOTDIR)/tools/automake.inc

