
URL := https://nlnetlabs.nl/downloads/unbound/unbound-1.16.3.tar.gz
CONFOPTS += --with-libexpat=$(STAGEDIR) --with-libunbound-only
CONFOPTS += --disable-gost --disable-ecdsa 

MAKEVARS = 
include $(ROOTDIR)/tools/automake.inc

