
URL := https://unbound.net/downloads/unbound-1.5.2.tar.gz
CONFOPTS += --with-libexpat=$(STAGEDIR) --with-libunbound-only
CONFOPTS += --disable-gost --disable-ecdsa 

MAKEVARS = 
include $(ROOTDIR)/tools/automake.inc

