URL = https://github.com/jbouse-debian/libgcgi/archive/debian/0.9.5.dfsg-7.tar.gz
BUILDDIR = libgcgi-debian-0.9.5.dfsg-7
PATCHES = libgcgi-debian-0.9.5.dfsg-7-extern-globals.patch
include $(ROOTDIR)/tools/automake.inc
