URL = https://ftp.gnu.org/gnu/osip/libosip2-2.2.0.tar.gz

export ACL_LICENSE = LGPL

CONFOPTS += --disable-dependency-tracking
CONFOPTS += --enable-static
CONFOPTS += --disable-shared

include $(ROOTDIR)/tools/automake.inc
