URL      = https://github.com/lloyd/yajl.git

# yajl has branches and tags with the same name, ensure we know what we are
# getting by using the hash.
# VERSION  = 2.1.0
VERSION  = a0ecdde0c042b9256170f2f8890dd9451a4240aa
METHOD   = git

include $(ROOTDIR)/tools/cmake.inc
