VERSION = 2.1.0
URL = https://downloads.sourceforge.net/project/traceroute/traceroute/traceroute-$(VERSION)/traceroute-$(VERSION).tar.gz
MAKEVARS = env=yes prefix=/

include $(ROOTDIR)/tools/automake.inc
