VERSION = 2.1.0
URL = https://sourceforge.net/projects/traceroute/files/traceroute/traceroute-$(VERSION)/traceroute-$(VERSION).tar.gz
MAKEVARS = env=yes prefix=/

include $(ROOTDIR)/tools/automake.inc
