VERSION = 1.0.225
URL = https://github.com/CESNET/libyang/archive/refs/tags/v$(VERSION).tar.gz
SRCDIR = libyang-$(VERSION)
BUILDDIR = libyang-$(VERSION)-build

CMAKE_OPTS += -DENABLE_LYD_PRIV=ON

include $(ROOTDIR)/tools/cmake.inc
