VERSION = 2.1.80
URL = https://github.com/CESNET/libyang/archive/refs/tags/v$(VERSION).tar.gz
SRCDIR = libyang-$(VERSION)
BUILDDIR = libyang-$(VERSION)-build

CMAKE_OPTS += -DCMAKE_BUILD_TYPE:String=Release

include $(ROOTDIR)/tools/cmake.inc
