#!/bin/sh
#
# Action for Digi/LR54 LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################

##############################################################
#exec 2>> /tmp/led.log
#set -x

findme_update() {
	FINDME=
	if find-me state &>/dev/null; then
		# flash WWAN service and signal strength LEDs green
		FINDME="-f WWAN1_SERVICE_GREEN -O WWAN1_SERVICE_YELLOW -f WWAN1_SIGNAL_GREEN -O WWAN1_SIGNAL_YELLOW"
		ledcmd $FINDME
		return 0
	fi
	return 1
}

case "$1" in
start)
	# Turn off all LEDs except SIMx
	for led in $(ls /sys/class/leds | grep -v SIM)
	do
		ledcmd -O $led
	done
	ledcmd -o POWER
	exit 0
	;;
reload)
	# LR54 units have no way of setting an altbit on/off, so if FindMe is enabled we
	# use that to set the LED state instead of determining the LED states based off
	# of the cellular/Wi-Fi statuses using the logic after this case statement
	findme_update && exit 0
	;;
stop)
	# Flash POWER LED
	ledcmd -F POWER
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

LEDCMD=

##############################################################
# Cellular LEDs

# The LR54 has one LED per modem for signal strength
# Off: No service.
# Yellow: Poor / Fair signal.
# Green: Good / Excellent signal.
update_signal_led() {
	local idx=$1

	case "$(runt get mm.modem.${idx}.status.bars)" in
		4|5) SIGNAL="-o WWAN1_SIGNAL_GREEN -O WWAN1_SIGNAL_YELLOW" ;;
		1|2|3) SIGNAL="-o WWAN1_SIGNAL_YELLOW -O WWAN1_SIGNAL_GREEN" ;;
		*) SIGNAL="-O WWAN1_SIGNAL_YELLOW -O WWAN1_SIGNAL_GREEN" ;;
	esac
}

# LR54 service LED
# Off: No service.
# Blinking Green: 2G/3G/4G connection is coming up.
# Solid Yellow: 2G or 3G connection is up.
# Solid Green: 4G connection is up.
update_service_led() {
	local idx=$1

	if [ "$(runt get mm.modem.${idx}.status.state)" = connected ]; then
		case "$(runt get mm.modem.${idx}.status.gtech)" in
			4g) SERVICE="-o WWAN1_SERVICE_GREEN -O WWAN1_SERVICE_YELLOW" ;;
			3g|2g) SERVICE="-o WWAN1_SERVICE_YELLOW -O WWAN1_SERVICE_GREEN" ;;
			*) SERVICE="-O WWAN1_SERVICE_YELLOW -O WWAN1_SERVICE_GREEN" ;;
		esac
	elif [ "$(runt get mm.modem.${idx}.status.state)" = connecting ]; then
		SERVICE="-f WWAN1_SERVICE_GREEN -O WWAN1_SERVICE_YELLOW"
	else
		SERVICE="-O WWAN1_SERVICE_YELLOW -O WWAN1_SERVICE_GREEN"
	fi
}

idx="$(modem idx 2>/dev/null)"

SIGNAL=
SERVICE=
update_signal_led ${idx}
update_service_led ${idx}

LEDCMD="${LEDCMD} ${SERVICE} ${SIGNAL}"

##############################################################

[ -z "${LEDCMD}" ] || eval ledcmd ${LEDCMD}

exit 0
