#
# Makefile -- Build instructions for Digi/LR54
#

#
# Note: this platform is using ATSHA204 chip bank 0 for signature verification
#

include lr54_common.mak

romfs: romfs.common
	echo "Digi LR54" > $(ROMFSDIR)/etc/issue
