#!/bin/sh
#
# Action for Connect IT 16 specific LED setting
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

wwan_led_update()
{
	WWAN_SERV=
	WWAN_SIG=

	idx="$(modem name=wwan idx || modem idx)" 2>/dev/null
	if [ -z "$idx" ]; then
		if sim -m | grep -qw yes; then
			# Slow flash SERV while waiting for modem to appear
			WWAN_SERV="-f WWAN_SERV_BLUE"
			WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED"
		else
			# No modem present at all. Everything off
			WWAN_SERV="-O WWAN_SERV_BLUE -O WWAN_SERV_RED"
			WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED"
		fi
	else
		case "$(runt get mm.modem.$idx.status.bars)" in
		5)   WWAN_SIG="-o WWAN_SIG_BLUE" ;;
		4|3) WWAN_SIG="-F WWAN_SIG_BLUE" ;;
		2|1) WWAN_SIG="-f WWAN_SIG_BLUE" ;;
		0)   WWAN_SIG="-f WWAN_SIG_RED" ;;
		*)   WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED" ;;
		esac

		if [ "$(runt get mm.modem.$idx.status.state)" = connected ]; then
			WWAN_SERV="-o WWAN_SERV_BLUE"
		elif [ -z "$(runt get mm.modem.$idx.modem.imsi)" ]; then
			# No SIM present
			WWAN_SERV="-o WWAN_SERV_RED"
		else
			# Connecting
			WWAN_SERV="-F WWAN_SERV_BLUE"
		fi
	fi
}

findme_update()
{
	FINDME=
	if find-me state &>/dev/null; then
		FINDME="-f STATUS_BLUE -f STATUS_REAR_BLUE"
	else
		FINDME="-o STATUS_BLUE -o STATUS_REAR_BLUE"
	fi
}

case "$1" in
start)
	ledcmd -O ALL -o POWER_BLUE -o STATUS_BLUE -o STATUS_REAR_BLUE
	;;
reload)
	findme_update
	wwan_led_update
	ledcmd $WWAN_SERV $WWAN_SIG $FINDME
	;;
stop)
	ledcmd -O ALL -f STATUS_BLUE -f STATUS_REAR_BLUE -o POWER_BLUE
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################
exit 0
