URL = https://gitlab.gnome.org/GNOME/libgudev.git
METHOD = git
VERSION = 233

AUTORECONF = NOCONFIGURE=yes ./autogen.sh

CONFOPTS += --disable-umockdev
CONFOPTS += --disable-gtk-doc-html

include $(ROOTDIR)/tools/automake.inc
