LIBPCIACCESS_VERSION = 0.16
URL = http://xorg.freedesktop.org/archive/individual/lib/libpciaccess-$(LIBPCIACCESS_VERSION).tar.bz2

CONFOPTS += --disable-static
 
include $(ROOTDIR)/tools/automake.inc
