LIBPCIACCESS_VERSION = 0.17
URL = https://xorg.freedesktop.org/archive/individual/lib/libpciaccess-$(LIBPCIACCESS_VERSION).tar.xz

CONFOPTS += --disable-static

CFLAGS += -D_LARGEFILE64_SOURCE
 
include $(ROOTDIR)/tools/automake.inc
