METHOD      = git
AUTORECONF  = (cd libpam ; ./bootstrap.sh)
CONFIGURE   = libpam/configure
URL         = https://github.com/google/google-authenticator.git
VERSION     = bd50d15c348a978c314d2b30e586fbc562096223
CONFVARS    +=
CONFOPTS    +=
MAKEVARS    =

include $(ROOTDIR)/tools/automake.inc
