dir_$(CONFIG_USER_PYTHON_MODULES_PIP)           += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_SETUPTOOLS)    += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_SIX)           += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_CFFI)          += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PYSERIAL)      += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PYSERIAL_ASYNCIO) += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PYMODBUS)      += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_BCRYPT)        += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PEXPECT)       += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PTYPROCESS)    += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_DIGI_XBEE_LIB) += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_AWS_SDK)       += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_SRP)           += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_PAHO_MQTT)     += python-modules
dir_$(CONFIG_USER_PYTHON_MODULES_HID)           += python-modules

dep_python_modules_y=
dep_python_modules_$(CONFIG_USER_PYTHON_MODULES_HID) += hidapi

python-modules: python $(dep_python_modules_y)
