VERSION = 20190702
URL = https://github.com/P-H-C/phc-winner-argon2/archive/$(VERSION).tar.gz

BUILDDIR = phc-winner-argon2-$(VERSION)

MAKEVARS = PREFIX= LIBRARY_REL=lib

include $(ROOTDIR)/tools/automake.inc
