URL = https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.6.4.tar.bz2
CONFVARS = GPG_ERROR_CONFIG=$(ROOTDIR)/lib/libgpg-error/build/libgpg-error-1.20-install/bin/gpg-error-config
MAKEVARS = 
include $(ROOTDIR)/tools/automake.inc
