VERSION  := 0.1a
URL      := https://www.monkey.org/~provos/libdnsres-$(VERSION).tar.gz

MAKEVARS :=		# defeat LIBTOOL override
include $(ROOTDIR)/tools/automake.inc
$(PKG)_AUTOCONF = autoreconf --install

