#!/bin/sh
#
# mkconfig -- convert from accelerated config to local .config
#
# Although the dist config sources the local config files it
# uses the fully qualified package/applet names. So we need to
# convert these now to the original local busybox small names.
#

grep CONFIG_USER_BUSYBOX_ $ROOTDIR/config/.config | \
	sed -e 's/CONFIG_USER_BUSYBOX_/CONFIG_/'

exit 0
