#!/bin/sh
#
# Generate Kconfigs for busbox that are distified versions of Config.in
#

mk_Kconfig()
{
	cat "$1" |
		sed \
		-e 's/mainmenu/comment/g' \
		-e 's/\(config[ 	]*\)\([A-Z][0-9A-Z_]*\)/\1USER_BUSYBOX_\2/g' \
		-e '/^[^a-zA-Z]*[ 	]*depends[ 	]/s/\([A-Z][0-9A-Z_]*\)/USER_BUSYBOX_\1/g' \
		-e '/^[^a-zA-Z]*[ 	]*default[ 	]/s/\([A-Z][A-Z][0-9A-Z_]*\)/USER_BUSYBOX_\1/g' \
		-e '/^[^a-zA-Z]*[ 	]*select[ 	]/s/\([A-Z][0-9A-Z_]*\)/USER_BUSYBOX_\1/g' \
		-e 's?\(^[ 	]*source[ 	][ 	]*\)\([a-zA-Z._].*\)/Config.in?\1../user/busybox/\2/Kconfig?' \
		> $2
}

make gen_build_files

find . -name Config.in | while read c
do
	echo "Processing $c ..."
	out=`dirname $c`/Kconfig
	mk_Kconfig "$c" "$out"
done
