
URL = http://www.nlnetlabs.nl/downloads/ldns/ldns-1.6.17.tar.gz
MAKEVARS = 
CONFOPTS += --disable-ldns-config
CONFOPTS += --disable-gost
CONFOPTS += --disable-ecdsa
include $(ROOTDIR)/tools/automake.inc

