
URL = https://www.nlnetlabs.nl/downloads/ldns/ldns-1.7.1.tar.gz
MAKEVARS = 
CONFOPTS += --disable-ldns-config
CONFOPTS += --disable-gost
CONFOPTS += --disable-ecdsa
CONFOPTS += --disable-dane-verify # Not available on OpenSSL versions earlier than 1.1.0
include $(ROOTDIR)/tools/automake.inc

