CONFIG_MIPS=y

CONFIG_ZONE_DMA=y
#CONFIG_RALINK_RT3052_MP2=y
#CONFIG_RALINK_RT3052=y
#CONFIG_RT3052_ASIC=y
#CONFIG_FLASH_REMAP_NEED=y
#CONFIG_RT2880_DRAM_32M=y
#CONFIG_MTD_NOR_RALINK=y
#CONFIG_RT2880_FLASH_8M=y
#CONFIG_RALINK_RAM_SIZE=32
#CONFIG_MTD_PHYSMAP_START=0xBF000000
#CONFIG_MTD_PHYSMAP_LEN=0x800000
#CONFIG_MTD_PHYSMAP_BUSWIDTH=2
#CONFIG_RT2880_ROOTFS_IN_FLASH=y
#CONFIG_MTD_KERNEL_PART_SIZ=0xD0000
CONFIG_MTD_3GDATA=y
CONFIG_RWSEM_GENERIC_SPINLOCK=y
CONFIG_GENERIC_FIND_NEXT_BIT=y
CONFIG_GENERIC_HWEIGHT=y
CONFIG_GENERIC_CALIBRATE_DELAY=y
CONFIG_GENERIC_TIME=y
CONFIG_SCHED_NO_NO_OMIT_FRAME_POINTER=y
CONFIG_DMA_NONCOHERENT=y
CONFIG_DMA_NEED_PCI_MAP_STATE=y
CONFIG_CPU_LITTLE_ENDIAN=y
CONFIG_SYS_SUPPORTS_LITTLE_ENDIAN=y
CONFIG_IRQ_CPU=y
CONFIG_SWAP_IO_SPACE=y
CONFIG_BOOT_ELF32=y
CONFIG_MIPS_L1_CACHE_SHIFT=5

CONFIG_CPU_MIPS32_R1=y
CONFIG_SYS_HAS_CPU_MIPS32_R1=y
CONFIG_SYS_HAS_CPU_MIPS32_R2=y
CONFIG_CPU_MIPS32=y
CONFIG_CPU_MIPSR1=y
CONFIG_SYS_SUPPORTS_32BIT_KERNEL=y
CONFIG_CPU_SUPPORTS_32BIT_KERNEL=y

CONFIG_32BIT=y
CONFIG_PAGE_SIZE_4KB=y
CONFIG_CPU_HAS_PREFETCH=y
CONFIG_MIPS_MT_DISABLED=y
CONFIG_CPU_HAS_LLSC=y
CONFIG_CPU_HAS_SYNC=y
CONFIG_GENERIC_HARDIRQS=y
CONFIG_GENERIC_IRQ_PROBE=y
CONFIG_CPU_SUPPORTS_HIGHMEM=y
CONFIG_ARCH_FLATMEM_ENABLE=y
CONFIG_SELECT_MEMORY_MODEL=y
CONFIG_FLATMEM_MANUAL=y
CONFIG_FLATMEM=y
CONFIG_FLAT_NODE_MEM_MAP=y
CONFIG_SPLIT_PTLOCK_CPUS=4
CONFIG_ZONE_DMA_FLAG=1
CONFIG_HZ_250=y
CONFIG_SYS_SUPPORTS_ARBIT_HZ=y
CONFIG_HZ=250
CONFIG_PREEMPT_NONE=y
CONFIG_LOCKDEP_SUPPORT=y
CONFIG_STACKTRACE_SUPPORT=y
CONFIG_DEFCONFIG_LIST="/lib/modules/$UNAME_RELEASE/.config"

CONFIG_EXPERIMENTAL=y
CONFIG_BROKEN_ON_SMP=y
CONFIG_INIT_ENV_ARG_LIMIT=32

CONFIG_LOCALVERSION=""
CONFIG_LOCALVERSION_AUTO=y
CONFIG_SYSVIPC=y
CONFIG_SYSVIPC_SYSCTL=y
CONFIG_BSD_PROCESS_ACCT=y
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_SYSCTL=y
CONFIG_EMBEDDED=y
CONFIG_SYSCTL_SYSCALL=y
CONFIG_HOTPLUG=y
CONFIG_PRINTK_FUNC=y
CONFIG_PRINTK=y
CONFIG_BUG=y
CONFIG_ELF_CORE=y
CONFIG_BASE_FULL=y
CONFIG_FUTEX=y
CONFIG_EPOLL=y
CONFIG_SHMEM=y
CONFIG_SLAB=y
CONFIG_TINY=y
CONFIG_PANIC=y
CONFIG_FULL_PANIC=y
CONFIG_MEMPOOL=y
CONFIG_AIO=y
CONFIG_XATTR=y
CONFIG_FILE_LOCKING=y
CONFIG_ETHTOOL=y
CONFIG_INETPEER=y
CONFIG_NET_SK_FILTER=y
CONFIG_NET_DEV_MULTICAST=y
CONFIG_IGMP=y
CONFIG_MAX_SWAPFILES_SHIFT=5
CONFIG_NR_LDISCS=16
CONFIG_MAX_USER_RT_PRIO=100
CONFIG_TINY_EXPERIMENTAL=y
CONFIG_PDFLUSH=y
CONFIG_BINFMT_ELF_AOUT=y
CONFIG_RT_MUTEXES=y
CONFIG_BASE_SMALL=0

CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y
CONFIG_MODVERSIONS=y
CONFIG_MODULE_SRCVERSION_ALL=y

CONFIG_BLOCK=y

CONFIG_IOSCHED_NOOP=y
CONFIG_DEFAULT_NOOP=y
CONFIG_DEFAULT_IOSCHED="noop"

CONFIG_MMU=y



CONFIG_BINFMT_ELF=y
CONFIG_TRAD_SIGNALS=y


CONFIG_NET=y

CONFIG_PACKET=y
CONFIG_PACKET_MMAP=y
CONFIG_UNIX=y
CONFIG_INET=y
CONFIG_IP_MULTICAST=y
CONFIG_IP_FIB_HASH=y
CONFIG_NET_IPIP=y
CONFIG_NET_IPGRE=y
CONFIG_IP_MROUTE=y
CONFIG_IP_PIMSM_V1=y
CONFIG_IP_PIMSM_V2=y
CONFIG_INET_TUNNEL=y
CONFIG_INET_DIAG=y
CONFIG_INET_TCP_DIAG=y
CONFIG_TCP_CONG_CUBIC=y
CONFIG_DEFAULT_TCP_CONG="cubic"

CONFIG_IPV6=y
CONFIG_NETFILTER=y
CONFIG_NETFILTER_DEBUG=y

CONFIG_NAT_RCONE=y
CONFIG_NF_CONNTRACK_ENABLED=y
CONFIG_NF_CONNTRACK_SUPPORT=y
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CT_ACCT=y
CONFIG_NF_CONNTRACK_MARK=y
CONFIG_NF_CONNTRACK_FTP=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_NETFILTER_XT_TARGET_CONNMARK=y
CONFIG_NETFILTER_XT_TARGET_DSCP=y
CONFIG_NETFILTER_XT_TARGET_MARK=y
CONFIG_NETFILTER_XT_TARGET_TCPMSS=y
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NETFILTER_XT_MATCH_DSCP=y
CONFIG_NETFILTER_XT_MATCH_HELPER=y
CONFIG_NETFILTER_XT_MATCH_LENGTH=y
CONFIG_NETFILTER_XT_MATCH_MAC=y
CONFIG_NETFILTER_XT_MATCH_MARK=y
CONFIG_NETFILTER_XT_MATCH_STATE=y
CONFIG_NETFILTER_XT_MATCH_LAYER7=y
CONFIG_NETFILTER_XT_MATCH_STRING=y
CONFIG_NETFILTER_XT_MATCH_WEBSTR=m
CONFIG_NETFILTER_XT_MATCH_TCPMSS=y

CONFIG_NF_CONNTRACK_IPV4=y
CONFIG_NF_CONNTRACK_PROC_COMPAT=y
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_REJECT=y
CONFIG_NF_NAT=y
CONFIG_NF_NAT_NEEDED=y
CONFIG_IP_NF_TARGET_MASQUERADE=y
CONFIG_IP_NF_TARGET_REDIRECT=y
CONFIG_NF_NAT_FTP=y
CONFIG_IP_NF_MANGLE=y
CONFIG_IP_NF_ARPTABLES=y





CONFIG_BRIDGE=y
CONFIG_VLAN_8021Q=y
CONFIG_LLC=y

CONFIG_NET_SCHED=y
CONFIG_NET_SCH_FIFO=y
CONFIG_NET_SCH_CLK_GETTIMEOFDAY=y

CONFIG_NET_SCH_HTB=y
CONFIG_NET_SCH_RED=y
CONFIG_NET_SCH_SFQ=y
CONFIG_NET_SCH_GRED=y
CONFIG_NET_SCH_DSMARK=y

CONFIG_NET_CLS=y
CONFIG_NET_CLS_TCINDEX=y
CONFIG_NET_CLS_FW=y

CONFIG_WIRELESS_EXT=y










CONFIG_MTD=y
CONFIG_MTD_PARTITIONS=y

CONFIG_MTD_CHAR=y
CONFIG_MTD_BLKDEVS=y
CONFIG_MTD_BLOCK=y

CONFIG_MTD_CFI=y
CONFIG_MTD_GEN_PROBE=y
CONFIG_MTD_MAP_BANK_WIDTH_1=y
CONFIG_MTD_MAP_BANK_WIDTH_2=y
CONFIG_MTD_MAP_BANK_WIDTH_4=y
CONFIG_MTD_CFI_I1=y
CONFIG_MTD_CFI_I2=y
CONFIG_MTD_CFI_AMDSTD=y
CONFIG_MTD_CFI_SSTSTD=y
CONFIG_MTD_CFI_UTIL=y

#CONFIG_MTD_RALINK=y

CONFIG_MTD_BLOCK2MTD=y






CONFIG_BLK_DEV_LOOP=y



CONFIG_SCSI=m
CONFIG_SCSI_PROC_FS=y

CONFIG_BLK_DEV_SR=m
CONFIG_BLK_DEV_SR_VENDOR=y









CONFIG_NETDEVICES=y


CONFIG_NET_ETHERNET=y
CONFIG_MII=y




CONFIG_NET_RADIO=y


CONFIG_PPP=y
CONFIG_PPP_MULTILINK=y
CONFIG_PPP_FILTER=y
CONFIG_PPP_ASYNC=y
CONFIG_PPP_SYNC_TTY=y
CONFIG_PPP_DEFLATE=y
CONFIG_PPP_BSDCOMP=y
CONFIG_PPP_MPPE=y
CONFIG_PPPOE=y
CONFIG_SLHC=y



CONFIG_INPUT=y




#CONFIG_RALINK_GPIO=y
#CONFIG_RALINK_GPIO_LED=y
CONFIG_SERIAL_NONSTANDARD=y
CONFIG_N_HDLC=y

CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_8250_NR_UARTS=2
CONFIG_SERIAL_8250_RUNTIME_UARTS=2
CONFIG_SERIAL_8250_EXTENDED=y

CONFIG_SERIAL_CORE=y
CONFIG_SERIAL_CORE_CONSOLE=y
CONFIG_UNIX98_PTYS=y
CONFIG_LEGACY_PTYS=y
CONFIG_LEGACY_PTY_COUNT=256














CONFIG_USB=y

CONFIG_USB_DEVICEFS=y


CONFIG_USB_ACM=m


CONFIG_USB_STORAGE=m






CONFIG_USB_SERIAL=m
CONFIG_USB_SERIAL_GENERIC=y
CONFIG_USB_SERIAL_AIRPRIME=m
CONFIG_USB_SERIAL_SIERRAWIRELESS=m
CONFIG_USB_SERIAL_OPTION=m
















CONFIG_FUSE_FS=y



CONFIG_PROC_FS=y
CONFIG_PROC_KCORE=y
CONFIG_PROC_SYSCTL=y
CONFIG_SYSFS=y
CONFIG_RAMFS=y

CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_EMBEDDED=y
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3
CONFIG_SQUASHFS_VMALLOC=y


CONFIG_PARTITION_ADVANCED=y
CONFIG_MSDOS_PARTITION=y

CONFIG_NLS=y
CONFIG_NLS_DEFAULT="iso8859-1"
CONFIG_NLS_ISO8859_1=y
CONFIG_NLS_UTF8=y



CONFIG_TRACE_IRQFLAGS_SUPPORT=y
CONFIG_LOG_BUF_SHIFT=14
CONFIG_CROSSCOMPILE=y
CONFIG_CMDLINE="console=ttyS1,115200n8 root=/dev/mtdblock4"


CONFIG_CRYPTO=y
CONFIG_CRYPTO_ALGAPI=y
CONFIG_CRYPTO_BLKCIPHER=y
CONFIG_CRYPTO_MANAGER=y
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_ECB=y
CONFIG_CRYPTO_CBC=m
CONFIG_CRYPTO_PCBC=m
CONFIG_CRYPTO_ARC4=y


CONFIG_CRC_CCITT=y
CONFIG_ZLIB_INFLATE=y
CONFIG_ZLIB_DEFLATE=y
CONFIG_TEXTSEARCH=y
CONFIG_TEXTSEARCH_KMP=y
CONFIG_TEXTSEARCH_BM=y
CONFIG_TEXTSEARCH_FSM=y
CONFIG_PLIST=y
CONFIG_HAS_IOMEM=y
CONFIG_HAS_IOPORT=y

#CONFIG_RALINK_RDM=y
#CONFIG_RAETH=y
#CONFIG_RAETH_CHECKSUM_OFFLOAD=y
#CONFIG_RT_3052_ESW=y
#CONFIG_LAN_WAN_SUPPORT=y
#CONFIG_WAN_AT_P0=y
#CONFIG_ESW_DOUBLE_VLAN_TAG=y
#CONFIG_RALINK_RT3050_1T1R=y
#CONFIG_RT2860V2_AP=m
#CONFIG_RT2860V2_AP_LED=y
#CONFIG_RT2860V2_AP_WSC=y
#CONFIG_RT2860V2_AP_LLTD=y
#CONFIG_RT2860V2_AP_WDS=y
#CONFIG_RT2860V2_AP_WMM_ACM=y
#CONFIG_RT2860V2_AP_MBSS=y
#CONFIG_RT2860V2_AP_APCLI=y
#CONFIG_RT2860V2_AP_IGMP_SNOOP=y
#CONFIG_RT2860V2_80211N_DRAFT3=y
#CONFIG_RT2860V2_STA=m
#CONFIG_RT2860V2_STA_WMM_ACM=y
#CONFIG_RT2860V2_STA_LED=y
#CONFIG_RT2860V2_STA_WSC=y
#CONFIG_RT2860V2_RT3XXX_STA_ANTENNA_DIVERSITY=y
#CONFIG_DWC_OTG=m
#CONFIG_DWC_OTG_HOST_ONLY=y
