#!/bin/sh
#
# Action for AnywhereUSB 2 specific LED setting
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

#
# NOTE: The AnywhereUSB 2 Plus hardware inverts the blue
#       power LED in hardware in order to force the LED
#       on as early as possible when power is applied.
#
#       The ledcmd parameters below must account for this.
#

findme_update()
{
	FINDME=
	if find-me state &>/dev/null; then
		# blue off, green on, red flashing
		FINDME="-o pwr1b -o pwr1g -F pwr1r"
	else
		# blue on, green off, red off
		FINDME="-O pwr1b -O pwr1g -O pwr1r"
	fi
}

case "$1" in
start|stop)
	# blue on, green off, red off
	ledcmd -O pwr1b -O pwr1g -O pwr1r
	;;
reload)
	findme_update
	ledcmd $FINDME
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################
exit 0
