
URL = https://libestr.adiscon.com/files/download/libestr-0.1.11.tar.gz
DOWNLOADHASH = 46632b2785ff4a231dcf241eeb0dcb5fc0c7d4da8ee49cf5687722cdbe8b2024

include $(ROOTDIR)/tools/automake.inc

$(PKG)_CONFOPTS =
$(PKG)_CONFOPTS += ac_cv_func_malloc_0_nonnull=yes
