
URL = http://libestr.adiscon.com/files/download/libestr-0.1.10.tar.gz
DOWNLOADHASH = bd655e126e750edd18544b88eb1568d200a424a0c23f665eb14bbece07ac703c

include $(ROOTDIR)/tools/automake.inc

$(PKG)_CONFOPTS =
$(PKG)_CONFOPTS += ac_cv_func_malloc_0_nonnull=yes
