#!/bin/bash

# This script can:
#   Power the cellular modem on or off via GPIO pins.
#   Match power state based on configured permissions in /etc/config/cellmodem.conf.
#

PWR_GPIO=243
COMMAND=$1
GPIODIR=/sys/class/gpio/gpio$PWR_GPIO

# Look for "CELLMODEM_DISABLE" to determine if cell modem can be enabled.
if [ -f /etc/config/cellmodem.conf ]; then
	 . /etc/config/cellmodem.conf
fi

if [ "$COMMAND" == "matchconfig" ]; then
	if [ "$CELLMODEM_DISABLE" ]; then
		COMMAND=off
	else
		COMMAND=on
	fi
fi

read VALUE <$GPIODIR/value

if [ "$COMMAND" == "off" ]
then
	if [ "$VALUE" == "1" ]; then
		echo `basename "$0"` "Powering down cellular modem."
		echo 0 >  $GPIODIR/value 
	fi
elif [ "$COMMAND" == "on" ]
then
	if [ -z "$CELLMODEM_DISABLE" ] && [ "$VALUE" == "0" ]; then
		echo `basename "$0"` "Powering up cellular modem."
		echo 1 > $GPIODIR/value
	fi
fi

exit $?
