#VERSION  = 2ce337dc2628b1af270341a5a7a81e361f4e355f
VERSION  = v1.3.0
METHOD   = git
URL      = https://github.com/relan/exfat.git

AUTORECONF := autoreconf --install

include $(ROOTDIR)/tools/automake.inc
