name: perl
version: 5.008008
abstract: Practical Extraction and Reporting Language
author: perl5-porters@perl.org
license: perl
distribution_type: core
private:
  directory:
    - ext/Cwd
    - ext/Data/Dumper
    - ext/DB_File
    - ext/Devel/PPPort
    - ext/Digest/MD5
    - ext/Encode
    - ext/Filter/Util/Call
    - ext/IO
    - ext/List/Util
    - ext/MIME/Base64
    - ext/Safe
    - ext/Storable
    - ext/Time/HiRes
    - ext/Unicode/Normalize
    - lib/Attribute/Handlers
    - lib/base
    - lib/bignum
    - lib/CGI
    - lib/Class/ISA
    - lib/CPAN
    - lib/Digest
    - lib/ExtUtils/t
    - lib/File/Spec
    - lib/File/Temp
    - lib/Filter/Simple
    - lib/Getopt/Long
    - lib/I18N/LangTags
    - lib/Locale/Maketext
    - lib/Math/BigFloat
    - lib/Math/BigInt
    - lib/Math/BigRat
    - lib/Memoize
    - lib/Net/FTP
    - lib/Net/Ping
    - lib/Net/t
    - lib/NEXT
    - lib/Pod/Perldoc
    - lib/Switch
    - lib/Term/ANSIColor
    - lib/Test/Harness
    - lib/Test/Simple
    - lib/Test/t
    - lib/Text/Balanced
    - lib/Text/TabsWrap
    - lib/Tie/File
    - lib/Unicode/Collate
    - t/lib/Filter/Simple
    - t/lib/MakeMaker
    - t/lib/Math
    - t/lib/sample-tests
    - t/lib/Test/Simple

  file:
    - ext/Compress/Zlib
    - ext/DynaLoader/t/XSLoader.t
    - ext/DynaLoader/XSLoader_pm.PL
    - ext/Filter/t/call.t
    - ext/Math/BigInt/FastCalc
    - lib/Archive/Tar
    - lib/Archive/Tar.pm
    - lib/Attribute/Handlers.pm
    - lib/base.pm
    - lib/bigint.pm
    - lib/bignum.pm
    - lib/bigrat.pm
    - lib/CGI.pm
    - lib/Class/ISA.pm
    - lib/CPAN.pm
    - lib/Cwd.pm
    - lib/Digest.pm
    - lib/encoding/warnings
    - lib/encoding/warnings.pm
    - lib/ExtUtils/CBuilder
    - lib/ExtUtils/CBuilder.pm
    - lib/ExtUtils/Command
    - lib/ExtUtils/Command.pm
    - lib/ExtUtils/Install.pm
    - lib/ExtUtils/Installed.pm
    - lib/ExtUtils/Liblist
    - lib/ExtUtils/Liblist.pm
    - lib/ExtUtils/MakeMaker
    - lib/ExtUtils/MakeMaker.pm
    - lib/ExtUtils/Manifest.pm
    - lib/ExtUtils/MANIFEST.SKIP
    - lib/ExtUtils/Mkbootstrap.pm
    - lib/ExtUtils/Mksymlists.pm
    - lib/ExtUtils/MM.pm
    - lib/ExtUtils/MM_AIX.pm
    - lib/ExtUtils/MM_Any.pm
    - lib/ExtUtils/MM_BeOS.pm
    - lib/ExtUtils/MM_Cygwin.pm
    - lib/ExtUtils/MM_DOS.pm
    - lib/ExtUtils/MM_MacOS.pm
    - lib/ExtUtils/MM_NW5.pm
    - lib/ExtUtils/MM_OS2.pm
    - lib/ExtUtils/MM_QNX.pm
    - lib/ExtUtils/MM_Unix.pm
    - lib/ExtUtils/MM_UWIN.pm
    - lib/ExtUtils/MM_VMS.pm
    - lib/ExtUtils/MM_VOS.pm
    - lib/ExtUtils/MM_Win32.pm
    - lib/ExtUtils/MM_Win95.pm
    - lib/ExtUtils/MY.pm
    - lib/ExtUtils/Packlist.pm
    - lib/ExtUtils/ParseXS
    - lib/ExtUtils/ParseXS.pm
    - lib/ExtUtils/testlib.pm
    - lib/fields.pm
    - lib/File/Spec.pm
    - lib/File/Temp.pm
    - lib/Filter/Simple.pm
    - lib/Getopt/Long.pm
    - lib/I18N/LangTags.pm
    - lib/if.pm
    - lib/if.t
    - lib/IO/Zlib
    - lib/IO/Zlib.pm
    - lib/Locale/Codes
    - lib/Locale/Constants.pm
    - lib/Locale/Constants.pod
    - lib/Locale/Country.pm
    - lib/Locale/Country.pod
    - lib/Locale/Currency.pm
    - lib/Locale/Currency.pod
    - lib/Locale/Language.pm
    - lib/Locale/Language.pod
    - lib/Locale/Maketext.pm
    - lib/Locale/Script.pm
    - lib/Locale/Script.pod
    - lib/Math/BigFloat.pm
    - lib/Math/BigInt.pm
    - lib/Math/BigRat.pm
    - lib/Memoize.pm
    - lib/Module/CoreList
    - lib/Module/CoreList.pm
    - lib/Net/ChangeLog.libnet
    - lib/Net/Cmd.pm
    - lib/Net/Config.eg
    - lib/Net/Config.pm
    - lib/Net/Domain.pm
    - lib/Net/FTP.pm
    - lib/Net/Hostname.eg
    - lib/Net/libnetFAQ.pod
    - lib/Net/Netrc.pm
    - lib/Net/NNTP.pm
    - lib/Net/Ping.pm
    - lib/Net/POP3.pm
    - lib/Net/README.libnet
    - lib/Net/SMTP.pm
    - lib/Net/Time.pm
    - lib/NEXT.pm
    - lib/PerlIO/via/QuotedPrint.pm
    - lib/PerlIO/via/t/QuotedPrint.t
    - lib/Pod/Checker.pm
    - lib/Pod/Escapes
    - lib/Pod/Escapes.pm
    - lib/Pod/Find.pm
    - lib/Pod/InputObjects.pm
    - lib/Pod/LaTeX.pm
    - lib/Pod/Man.pm
    - lib/Pod/ParseLink.pm
    - lib/Pod/Parser.pm
    - lib/Pod/ParseUtils.pm
    - lib/Pod/Perldoc.pm
    - lib/Pod/PlainText.pm
    - lib/Pod/Select.pm
    - lib/Pod/Simple
    - lib/Pod/Simple.pm
    - lib/Pod/Simple.pod
    - lib/Pod/t/basic.cap
    - lib/Pod/t/basic.clr
    - lib/Pod/t/basic.man
    - lib/Pod/t/basic.ovr
    - lib/Pod/t/basic.pod
    - lib/Pod/t/basic.t
    - lib/Pod/t/basic.txt
    - lib/Pod/t/man.t
    - lib/Pod/t/parselink.t
    - lib/Pod/t/pod2latex.t
    - lib/Pod/t/text-errors.t
    - lib/Pod/t/text-options.t
    - lib/Pod/t/text.t
    - lib/Pod/Text.pm
    - lib/Pod/Text/Color.pm
    - lib/Pod/Text/Overstrike.pm
    - lib/Pod/Text/Termcap.pm
    - lib/Pod/Usage.pm
    - lib/Switch.pm
    - lib/Term/ANSIColor.pm
    - lib/Term/Cap.pm
    - lib/Term/Cap.t
    - lib/Test.pm
    - lib/Test/Builder.pm
    - lib/Test/Harness.pm
    - lib/Test/More.pm
    - lib/Test/Simple.pm
    - lib/Text/Balanced.pm
    - lib/Text/Tabs.pm
    - lib/Text/Wrap.pm
    - lib/Tie/File.pm
    - lib/Time/Local.pm
    - lib/Time/Local.t
    - lib/Unicode/Collate.pm
    - pod/pod2man.PL
    - pod/pod2text.PL
    - pod/pod2usage.PL
    - pod/podchecker.PL
    - pod/podselect.PL
    - t/lib/filter-util.pl
    - t/lib/TieIn.pm
    - t/lib/TieOut.pm
    - t/lib/ZlibTestUtils.pm
    - t/pod/emptycmd.t
    - t/pod/emptycmd.xr
    - t/pod/find.t
    - t/pod/for.t
    - t/pod/for.xr
    - t/pod/headings.t
    - t/pod/headings.xr
    - t/pod/include.t
    - t/pod/include.xr
    - t/pod/included.t
    - t/pod/included.xr
    - t/pod/lref.t
    - t/pod/lref.xr
    - t/pod/multiline_items.t
    - t/pod/multiline_items.xr
    - t/pod/nested_items.t
    - t/pod/nested_items.xr
    - t/pod/nested_seqs.t
    - t/pod/nested_seqs.xr
    - t/pod/oneline_cmds.t
    - t/pod/oneline_cmds.xr
    - t/pod/pod2usage.t
    - t/pod/pod2usage.xr
    - t/pod/poderrs.t
    - t/pod/poderrs.xr
    - t/pod/podselect.t
    - t/pod/podselect.xr
    - t/pod/special_seqs.t
    - t/pod/special_seqs.xr
    - t/pod/testcmp.pl
    - t/pod/testp2pt.pl
    - t/pod/testpchk.pl

