VERSION = 2.5.4
URL = https://github.com/seccomp/libseccomp/releases/download/v$(VERSION)/libseccomp-$(VERSION).tar.gz
DOWNLOADHASH = d82902400405cf0068574ef3dc1fe5f5926207543ba1ae6f8e7a1576351dcbdb

MAKEVARS =

include $(ROOTDIR)/tools/automake.inc
