URL = https://github.com/ColinIanKing/stress-ng.git
METHOD = git
VERSION = V0.15.08
iperf_PKG = stress-ng-$(VERSION)

LDFLAGS += -static
CFLAGS += -DBUILD_STATIC

include $(ROOTDIR)/tools/automake.inc

