URL = ftp://mcrypt.hellug.gr/pub/crypto/mcrypt/libmcrypt/libmcrypt-2.5.7.tar.gz

CONFOPTS += --with-included-algos="yes"
CONFOPTS += --enable-dynamic-loading=no
CONFOPTS += --enable-shared
CONFOPTS += --disable-static

# avoid jlibtool
MAKEVARS = 

include $(ROOTDIR)/tools/automake.inc
