#!/usr/bin/env python3

import kcheck
import product
import os
import sys
from operator import itemgetter

ret = 0

for p in sorted(product.products.values(), key=itemgetter('vendor', 'product')):
    print(f"Checking: {p['vendor']}/{p['product']}")
    kconfig = kcheck.Config(
        product.products,
        f"vendors/{p['vendor']}/{p['product']}",
        product=p)
    kproduct = kcheck.Product(kconfig, product.products, product.groups)
    errors = kproduct.check()
    if errors:
        kproduct.print_errors(errors)
        print("")
        ret = 1

sys.exit(ret)

