#!/usr/bin/env python

import kcheck
import product
import os
import sys

ret = 0
for p in product.products.itervalues():
    print 'Checking: %s/%s' % (p['vendor'], p['product'])
    kconfig = kcheck.Config(product.products, 'vendors/%s/%s' % (p['vendor'], p['product']))
    kproduct = kcheck.Product(kconfig, product.products, product.groups)
    if kproduct.check(kconfig):
        ret = 1
sys.exit(ret)
