#!/usr/bin/env python3

import kcheck
import product
import argparse
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument('dir', nargs='?', default=os.getcwd())
args = parser.parse_args()

kconfig = kcheck.Config(product.products, args.dir)
kproduct = kcheck.Product(kconfig, product.products, product.groups)
errors = kproduct.check()
if errors:
	kproduct.print_errors(errors)

sys.exit(1 if errors else 0)

