#!/usr/bin/env python

import kcheck
import product
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('dir', nargs='?', default=os.getcwd())
parser.add_argument('--set-only', action='store_true', default=False)
args = parser.parse_args()

kconfig = kcheck.Config(product.products, args.dir)
kproduct = kcheck.Product(kconfig, product.products, product.groups)

if args.set_only:
    kproduct.set_only(kconfig)
else:
    kproduct.set(kconfig)
