#!/usr/bin/env python

import kcheck
import product

for p in product.products.itervalues():
    print 'Setting: %s/%s' % (p['vendor'], p['product'])
    kconfig = kcheck.Config(product.products, 'vendors/%s/%s' % (p['vendor'], p['product']))
    kproduct = kcheck.Product(kconfig, product.products, product.groups)
    kproduct.set(kconfig)
