#!/usr/bin/env python3

import kcheck
import product
import argparse
import os
import sys
import json


parser = argparse.ArgumentParser()
parser.add_argument('dir', nargs='?', default=os.getcwd())
args = parser.parse_args()

try:
	kconfig = kcheck.Config(product.products, args.dir)
	kproduct = kcheck.Product(kconfig, product.products, product.groups)
	feature_dict = json.dumps({kconfig.product['product']: kcheck.test(kproduct)})
	print(feature_dict)

except Exception:
	sys.exit(1)
