#!/usr/bin/env python3

import kcheck
import product
import os
import sys
import json
from operator import itemgetter

try:
    feature_dict = {}
    for p in sorted(product.products.values(), key=itemgetter('vendor', 'product')):
        print('Checking: %s/%s' % (p['vendor'], p['product']))
        kconfig = kcheck.Config(product.products, 'vendors/%s/%s' % (p['vendor'], p['product']))
        kproduct = kcheck.Product(kconfig, product.products, product.groups)
        feature_dict[p['product']] = kproduct.test(kconfig)

except Exception:
    sys.exit(1)

print(json.dumps(feature_dict))
