#!/bin/sh
#
# Action for 8300 LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

case "$1" in
start)
	ledcmd -a -N ALL
	exit 0
	;;
reload)
	;;
stop)
	# Firmware flash
	ledcmd -a -n ALL -f ALL
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################

# Find the primary modem, or alternatively *any* modem
modem_name="$(modem name 2> /dev/null)"
idx="$(modem name="$modem_name" idx 2> /dev/null)"
# Find the first interface on the modem
for i in $(runt keys mm.map.interface_idx); do
	[ "$(runt get mm.map.interface_idx.$i)" = "$idx" ] \
		&& intf=$i && break
done

if [ "$(runt get network.interface.$intf.ipv4.up)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.up)" = 1 ]; then
	[ "$(runt get surelink.ipv4_interface_$intf.passed)" != n ] \
		&& [ "$(runt get surelink.ipv6_interface_$intf.passed)" != n ] \
		&& CELL=2 || CELL=1
elif [ "$(runt get network.interface.$intf.ipv4.pending)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.pending)" = 1 ]; then
	CELL=1
else
	CELL=0 # not-valid, never going to work
fi

if [ "$CELL" != 0 -a "$modem_name" ]; then
	case "$(runt get mm.modem.$modem_name.status.bars)" in
	5) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -o RSS5" ;;
	4) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -O RSS5" ;;
	3) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -O RSS4 -O RSS5" ;;
	2) SIGNAL="-o RSS1 -o RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	1) SIGNAL="-o RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	*) SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	esac

	case "$(runt get mm.modem.$modem_name.status.gtech)" in
	4g) RAT="-O 3g -o 4g" ;;
	3g) RAT="-o 3g -O 4g" ;;
	*)  RAT="-O 3g -O 4g" ;;
	esac

	case "$(runt get mm.modem.$modem_name.modem.imsi)" in
	unkn*|none|'') SIM="-o mdm" ;;
	*)             SIM="-O mdm" ;;
	esac
else
	SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5"
	RAT="-O 3g -O 4g"
	SIM="-O mdm"
fi

case "$CELL" in
2) CELL="-o USB" ;;
1) CELL="-f USB" ;;
*) CELL="-O USB" ;;
esac

##############################################################

LINK=$(ip link show eth0 2> /dev/null | grep -c "state UP")

LAN4=-1
LAN6=-1
if [ "$LINK" = 1 ]; then
	case $(runt get network.interface.lan.ipv4.up) in
	1) [ "$(runt get surelink.ipv4_interface_lan.passed)" = n ] && LAN4=1 || LAN4=2 ;;
	0) [ "$(runt get network.interface.lan.ipv4.pending)" = 1 ] && LAN4=1 || LAN4=0 ;;
	esac

	case $(runt get network.interface.lan.ipv6.up) in
	1) [ "$(runt get surelink.ipv6_interface_lan.passed)" = n ] && LAN6=1 || LAN6=2 ;;
	0) [ "$(runt get network.interface.lan.ipv6.pending)" = 1 ] && LAN6=1 || LAN6=0 ;;
	esac
fi

if [ "$LAN4" = -1 -a "$LAN6" = -1 ]; then
	# if neither interface exists, match link
	LAN=$((LINK ? 2 : 0))
elif [ "$LAN4" = 2 -o "$LAN6" = 2 ]; then
	LAN=2
elif [ "$LAN4" = 1 -o "$LAN6" = 1 ]; then
	LAN=1
else
	LAN=0
fi

case "$LAN" in
2) LAN="-o ONLINE" ;;
1) LAN="-f ONLINE" ;;
*) LAN="-O ONLINE" ;;
esac

##############################################################

ledcmd $CELL $LAN
[ -x /usr/bin/ftdi-led ] && /usr/bin/ftdi-led $SIGNAL $RAT $SIM

exit 0
