#!/bin/sh

#
# mkffs -- make flash filesystem for AC8300 NAND
#
# Create and partition a UBI flash region over most of the nand flash.
# This is best for UBI, we want bad blocking and wear leveling over most
# of the flash for best results.
#

MTDEVICE=/dev/mtd3
UBINUM=0
UBIDEVICE=/dev/ubi0

# Check if we are running from mounted root on UBI first?

#
# Creat and attach the single large UBI region.
#
ubiformat -y $MTDEVICE
ubiattach -p $MTDEVICE -d $UBINUM

#
# Create the filesystem partitions we want.
#
ubimkvol $UBIDEVICE -N image -s 30MiB
ubimkvol $UBIDEVICE -N config -s 4MiB
ubimkvol $UBIDEVICE -N recover -s 10MiB
ubimkvol $UBIDEVICE -N recover_images -s 44MiB
ubimkvol $UBIDEVICE -N extra -s 24MiB

exit 0
