ACL_LICENSE = MIT
ACL_PKG     = Loki
export ACL_PKG ACL_LICENSE

URL = https://sourceforge.net/projects/loki-lib/files/Loki/Loki%200.1.7/loki-0.1.7.tar.bz2
BUILD = build-shared
MAKEVARS = prefix=/
include $(ROOTDIR)/tools/automake.inc
