#!/bin/sh
#
# Action for 5400-RM/5401-RM/5400-LX LEDs
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

LED_4G='LAN3_RX'
LED_3G='LAN3_TX'

# flash Online, LTE, 3G, Backup, and signal strength LEDs green
findme_update() {
	FINDME=
	if find-me state &>/dev/null; then
		FINDME="-a -n $LED_4G -n $LED_3G -n ONLINE -n ETH -n COM -n RSS1 -n RSS2 -n RSS3 -n RSS4 -n RSS5 -f $LED_4G -f $LED_3G -f ETH -f COM -f ONLINE -f RSS1 -f RSS2 -f RSS3 -f RSS4 -f RSS5"
	else
		FINDME="-a -N $LED_4G -N $LED_3G -N COM -N ETH -N ONLINE -N RSS1 -N RSS2 -N RSS3 -N RSS4 -N RSS5"
	fi
	ledcmd $FINDME
}

case "$1" in
start)
	ledcmd -a -N ALL
	exit 0
	;;
reload)
	findme_update
	;;
stop)
	# Firmware flash
	ledcmd -a -n ALL -f ALL
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################

# Find the primary modem, or alternatively *any* modem
idx="$(modem name=modem idx 2> /dev/null)" || idx="$(modem idx 2> /dev/null)"
# Find the first interface on the modem
for i in $(runt keys mm.map.interface_idx); do
	[ "$(runt get mm.map.interface_idx.$i)" = "$idx" ] \
		&& intf=$i && break
done

if [ "$(runt get network.interface.$intf.ipv4.up)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.up)" = 1 ]; then
	[ "$(runt get surelink.ipv4_interface_$intf.passed)" != n ] \
		&& [ "$(runt get surelink.ipv6_interface_$intf.passed)" != n ] \
		&& CELL=2 || CELL=1
elif [ "$(runt get network.interface.$intf.ipv4.pending)" = 1 ] \
		|| [ "$(runt get network.interface.$intf.ipv6.pending)" = 1 ]; then
	CELL=1
else
	CELL=0 # not-valid, never going to work
fi

if [ "$CELL" != 0 ]; then
	case "$(runt get mm.modem.$idx.status.bars)" in
	5) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -o RSS5" ;;
	4) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -o RSS4 -O RSS5" ;;
	3) SIGNAL="-o RSS1 -o RSS2 -o RSS3 -O RSS4 -O RSS5" ;;
	2) SIGNAL="-o RSS1 -o RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	1) SIGNAL="-o RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	*) SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5" ;;
	esac

	case "$(runt get mm.modem.$idx.status.gtech)" in
	4g) RAT="-o LAN3_RX -O LAN3_TX" ;;
	3g) RAT="-O LAN3_RX -o LAN3_TX" ;;
	*)  RAT="-O LAN3_RX -O LAN3_TX" ;;
	esac
else
	SIGNAL="-O RSS1 -O RSS2 -O RSS3 -O RSS4 -O RSS5"
	RAT="-O LAN3_RX -O LAN3_TX"
fi

case "$CELL" in
2) CELL="-o ONLINE" ;;
1) CELL="-f ONLINE" ;;
*) CELL="-O ONLINE" ;;
esac

##############################################################

LINK=$(ip link show eth0 2> /dev/null | grep -c "state UP")

LAN4=-1
LAN6=-1
if [ "$LINK" = 1 ]; then
	case $(runt get network.interface.lan.ipv4.up) in
	1) [ "$(runt get surelink.ipv4_interface_lan.passed)" = n ] && LAN4=1 || LAN4=2 ;;
	0) [ "$(runt get network.interface.lan.ipv4.pending)" = 1 ] && LAN4=1 || LAN4=0 ;;
	esac

	case $(runt get network.interface.lan.ipv6.up) in
	1) [ "$(runt get surelink.ipv6_interface_lan.passed)" = n ] && LAN6=1 || LAN6=2 ;;
	0) [ "$(runt get network.interface.lan.ipv6.pending)" = 1 ] && LAN6=1 || LAN6=0 ;;
	esac
fi

if [ "$LAN4" = -1 -a "$LAN6" = -1 ]; then
	# if neither interface exists, match link
	LAN=$((LINK ? 2 : 0))
elif [ "$LAN4" = 2 -o "$LAN6" = 2 ]; then
	LAN=2
elif [ "$LAN4" = 1 -o "$LAN6" = 1 ]; then
	LAN=1
else
	LAN=0
fi

case "$LAN" in
2) LAN="-o ETH" ;;
1) LAN="-f ETH" ;;
*) LAN="-O ETH" ;;
esac

##############################################################

ledcmd $LAN $CELL $RAT $SIGNAL

exit 0
