#!/bin/sh
# This script gets run when the device is in no-crypto mode
# It enables the telnetd service, the basic configs auth
#   the authentication service (pam), assigns an IP to the
#   device, and starts inetd service before existing
exec > /dev/console 2>&1

# This only runs when .nocrypt doesn't exist
if [ ! -e /etc/config/.nocrypt ] ; then
  touch /etc/config/.nocrypt
  flatfsd -i
  exit 0
fi

[ -f /var/run/flatfsd.pid ] || flatfsd &
echo "23 stream tcp nowait root /bin/telnetd" >> /etc/inetd.conf
cat > /etc/config/accns.json <<!EOF
{
  "auth": {
    "group": {
      "admin": {
        "acl": {
          "admin": {
            "enable": false
          },
          "shell": {
            "enable": true
          }
        }
      }
    }
  }
}
!EOF
/etc/action.d/pam start
ifconfig eth0 192.168.210.1
inetd &
