#
# Switch to using the git repo to get latest fixes. There has been no
# official package release since 2020.
#
URL     = https://github.com/libconfuse/libconfuse.git
VERSION = 38d637245729096c301c801db9813ba69ee1542f
METHOD  = git

AUTORECONF = ./autogen.sh

include $(ROOTDIR)/tools/automake.inc
