VERSION = 4.4.36
URL = https://github.com/besser82/libxcrypt/releases/download/v$(VERSION)/libxcrypt-$(VERSION).tar.xz

CONFOPTS += --enable-obsolete-api=no
CONFOPTS += --disable-xcrypt-compat-files
CONFOPTS += --disable-symvers

include $(ROOTDIR)/tools/automake.inc
