
CONFOPTS  = --disable-nls
CONFOPTS += --disable-example
CONFOPTS += --disable-kernel-module
CONFOPTS += --enable-lib
CONFOPTS += --enable-util

MAKEVARS  = LIBS=-lpthread

URL = https://github.com/libfuse/libfuse/releases/download/fuse_2_9_4/fuse-2.9.2.tar.gz

include $(ROOTDIR)/tools/automake.inc

