URL      = https://git.openwrt.org/project/ubus.git
VERSION = 2bebf93cd3343fe49f22a05ef935e460d2d44f67 # 22.03.6
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0 -DBUILD_EXAMPLES=0 -DENABLE_SYSTEMD=0

include $(ROOTDIR)/tools/cmake.inc

