URL      = git://nbd.name/luci2/ubus.git
VERSION  = 2d660c519d2fcff95248da9f4fd9b37d61f9eb09
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0 -DBUILD_EXAMPLES=0 -DENABLE_SYSTEMD=0

include $(ROOTDIR)/tools/cmake.inc

