URL      = https://git.openwrt.org/project/ubus.git
VERSION  = 221ce7e7ff1bd1a0c9995fa9d32f58e865f7207f
METHOD   = git
CMAKE_OPTS = -DBUILD_LUA=0 -DBUILD_EXAMPLES=0 -DENABLE_SYSTEMD=0

include $(ROOTDIR)/tools/cmake.inc

