#!/bin/sh

#
# mkffs -- make MMC flash filesystem for awusb2c
#
# Setup and create partitions on the MMC flash device.
#

MMC=/dev/mmcblk0

parted -s ${MMC} mktable gpt
parted -s ${MMC} mkpart image 2048s 186367s
parted -s ${MMC} mkpart image1 186368s 370687s
parted -s ${MMC} mkpart opt ext4 370688s 3666MB

mkfs.ext4 -F ${MMC}p3

exit 0
