
METHOD      = git
URL         = https://github.com/shellinabox/shellinabox.git
VERSION     = f67073d33eb4707efc5dcab08e7b787dcaae57af
CONFOPTS    = --disable-pam --disable-runtime-loading
CFLAGS     += -Dupdwtmp=failed
AUTORECONF  = autoreconf -i

include $(ROOTDIR)/tools/automake.inc

