#!/bin/sh
#
# Action for Connect IT 48 specific LED setting
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

wwan_led_update()
{
	WWAN_SERV=
	WWAN_SIG=

	MODEM_STATUS=$(runt get mm.persist.port.module.status)
	if [ "$MODEM_STATUS" = "Updating firmware" ]; then
		WWAN_SERV="-O WWAN_SERV_BLUE -f WWAN_SERV_RED"
		WWAN_SIG="-O WWAN_SIG_BLUE -f WWAN_SIG_RED"
	elif [ "$MODEM_STATUS" = "Recovering firmware" ]; then
		WWAN_SERV="-O WWAN_SERV_RED -f WWAN_SERV_BLUE"
		WWAN_SIG="-O WWAN_SIG_RED -f WWAN_SIG_BLUE"
	else
		modem_name="$(modem name)" 2>/dev/null
		if [ -z "$modem_name" ]; then
			if sim -m 2>/dev/null | grep -qw yes; then
				# Slow flash SERV while waiting for modem to appear
				WWAN_SERV="-O WWAN_SERV_RED -f WWAN_SERV_BLUE"
				WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED"
			else
				# No modem present at all. Everything off
				WWAN_SERV="-O WWAN_SERV_BLUE -O WWAN_SERV_RED"
				WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED"
			fi
		else
			case "$(runt get mm.modem.$modem_name.status.bars)" in
			5)   WWAN_SIG="-O WWAN_SIG_RED -o WWAN_SIG_BLUE" ;;
			4|3) WWAN_SIG="-O WWAN_SIG_RED -F WWAN_SIG_BLUE" ;;
			2|1) WWAN_SIG="-O WWAN_SIG_RED -f WWAN_SIG_BLUE" ;;
			0)   WWAN_SIG="-O WWAN_SIG_BLUE -f WWAN_SIG_RED" ;;
			*)   WWAN_SIG="-O WWAN_SIG_BLUE -O WWAN_SIG_RED" ;;
			esac

			if [ "$(runt get mm.modem.$modem_name.status.state)" = connected ]; then
				WWAN_SERV="-O WWAN_SERV_RED -o WWAN_SERV_BLUE"
			elif [ -z "$(runt get mm.modem.$modem_name.modem.imsi)" ]; then
				# No SIM present
				WWAN_SERV="-O WWAN_SERV_BLUE -o WWAN_SERV_RED"
			else
				# Connecting
				WWAN_SERV="-O WWAN_SERV_RED -F WWAN_SERV_BLUE"
			fi
		fi
	fi
}

findme_update()
{
	FINDME=
	if find-me state &>/dev/null; then
		FINDME="-f STATUS_BLUE -f STATUS_REAR_BLUE"
	else
		FINDME="-o STATUS_BLUE -o STATUS_REAR_BLUE"
	fi
}

case "$1" in
start)
	ledcmd -O ALL -o POWER_BLUE -o STATUS_BLUE -o STATUS_REAR_BLUE
	;;
reload)
	findme_update
	wwan_led_update
	ledcmd $WWAN_SERV $WWAN_SIG $FINDME
	;;
stop)
	ledcmd -O ALL -f STATUS_BLUE -f STATUS_REAR_BLUE -o POWER_BLUE
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################
exit 0
