#!/bin/sh

#
# mkinitrd -- construct an initrd filesystem for Connect IT 48
#
# This constructs a small loader root filesystem for the ConnectIT48. It is run
# by the kernel at boot, and is intended to verify, mount and switch
# to the real flash based root filesystem.
#
# FIXME: this needs to handle image verification
#

if [ $# != 1 ] ; then
	echo "usage: mkinitrd <ROOTDIR>"
	exit 1
fi

ROOTDIR=$1
BUILDDIR=$(pwd)
INITRD=$ROOTDIR/initrd
ROMFS=$ROOTDIR/romfs
echo "Constructing initrd in $INITRD"

mkdir -p $INITRD
rm -rf $INITRD/*
cd $INITRD

echo "Populating initrd..."
mkdir bin dev etc lib mnt old proc sbin sys usr usr/bin usr/sbin
ln -s lib lib64

cd dev
touch @mem,c,1,1
touch @kmem,c,1,2
touch @null,c,1,3
touch @zero,c,1,5
touch @tty,c,5,0
touch @console,c,5,1
touch @ttyS0,c,4,64
touch @sda,b,8,0
touch @sda1,b,8,1
touch @sda2,b,8,2
touch @sda3,b,8,3
touch @sda4,b,8,4
touch @sda5,b,8,5
touch @sda6,b,8,6
touch @sda7,b,8,7
touch @sda8,b,8,8
cd $INITRD

COPYLIST="bin/busybox bin/cat bin/chgrp bin/chmod bin/chown bin/cp bin/date bin/dd bin/df bin/echo bin/egrep bin/false bin/fgrep bin/grep bin/init bin/ln bin/ls bin/mkdir bin/mknod bin/mktemp bin/more bin/mount bin/mv bin/pidof bin/ps bin/pwd bin/rm bin/rmdir bin/sh bin/sleep bin/stty bin/sync bin/touch bin/true bin/umount bin/vi sbin/halt sbin/pivot_root sbin/poweroff sbin/reboot usr/bin/[ usr/bin/head usr/bin/find usr/bin/xargs usr/bin/du usr/bin/tty lib/ld-linux*.so.2 lib/ld64-uClibc*.so* lib/libc.so.0 lib/libm.so* lib/libm-*.so lib/libcrypt*.so* lib/libuClibc*.so* lib/libpam* lib/libdl* lib/libgcc*"

for FILE in $COPYLIST
do
        cp -a $ROMFS/$FILE $INITRD/`dirname $FILE`
done

cd $BUILDDIR
cp rc.initrd $INITRD/etc/rc
chmod 755 $INITRD/etc/rc

exit 0
