URL = https://www.kernel.org/pub/software/network/ethtool/ethtool-6.7.tar.gz
CONFOPTS = $(if $(CONFIG_USER_ETHTOOL_PRETTY_DUMP),--enable-pretty-dump,--disable-pretty-dump)
include $(ROOTDIR)/tools/automake.inc
