#!/bin/sh
#
# Action for TX64 specific LED setting
#
##############################################################
# allow script override
[ -x /etc/config/led ] && exec /etc/config/led "$@"
##############################################################
#exec 2>> /tmp/led.log
#set -x

case "$1" in
start)
	ledcmd -O ALL -o POWER
	exit 0
	;;
reload)
	;;
stop)
	# Firmware flash
	ledcmd -F POWER
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|reload}"
	exit 1
	;;
esac

##############################################################
# Update wifi leds
runt update network.wifi
eval $(config stop)
eval $(config start)
config load

led1=0
led2=0
aps=$(config keys network.wifi.ap)
for ap in $aps ; do
    ap=${ap%%.*}
    device="$(runt get network.wifi.ap.$ap.device)"
    if [ -n "$device" ]; then
        if ip link show $device up | grep -q "state UP"; then
            radio=$(config dump network.wifi.ap.$ap.radio)
            num="${radio//[![0-9]/}"
            [ $num = "1" ] && led1=1 || led2=1
        fi
    fi
done

clients=$(config keys network.wifi.client)
for client in $clients ; do
    client=${client%%.*}
    device="$(runt get network.wifi.client.$client.device)"
    if [ -n "$device" ]; then
        if ip link show $device up | grep -q "state UP"; then
            radio=$(config dump network.wifi.client.$client.radio)
            num="${radio//[![0-9]/}"
            [ $num = "1" ] && led1=1 || led2=1
        fi
    fi
done
eval $(config stop)

LED00="-O WIFI1 -O WIFI2" # both wifi leds off
LED10="-o WIFI1 -O WIFI2" # wifi1 on wifi2 off
LED01="-O WIFI1 -o WIFI2" # wifi1 off wifi2 on
LED11="-o WIFI1 -o WIFI2" # both wifi leds on

eval ledcmd \$LED$led1$led2

##############################################################
# Cellular LEDs

eval $(config start)
config load
MODEM_NAMES="$(config keys network.modem)"
eval $(config stop)

WWAN_LEDS="WWAN1 WWAN2"

# The TX64 has one LED per modem for signal strength
# Off: No service.
# Yellow: Poor / Fair signal.
# Green: Good / Excellent signal.
create_signal_led_args() {
	wwan=$1
	bars=$2

	case "$bars" in
		5) SIGNAL="-o ${wwan}_SIGNAL_GREEN" ;;
		4) SIGNAL="-o ${wwan}_SIGNAL_GREEN" ;;
		3) SIGNAL="-o ${wwan}_SIGNAL_YELLOW" ;;
		2) SIGNAL="-o ${wwan}_SIGNAL_YELLOW" ;;
		1) SIGNAL="-o ${wwan}_SIGNAL_YELLOW" ;;
		*) SIGNAL="-O ${wwan}_SIGNAL_YELLOW -O ${wwan}_SIGNAL_GREEN" ;;
	esac
}

# TX64 service LED
# Blinking Green: 2G/3G/4G connection is coming up.
# Solid Yellow: 2G or 3G connection is up.
# Solid Green: 4G connection is up.
# Off: Everything else.
create_service_led_args() {
	wwan=$1
	state=$2
	tech=$3

	if [ "$state" = connected ]; then
		case "$tech" in
			4g) SERVICE="-o ${wwan}_SERVICE_GREEN" ;;
			3g) SERVICE="-o ${wwan}_SERVICE_YELLOW" ;;
			2g) SERVICE="-o ${wwan}_SERVICE_YELLOW" ;;
			*) SERVICE="-O ${wwan}_SERVICE_YELLOW -O ${wwan}_SERVICE_GREEN" ;;
		esac
	elif [ "$state" = connecting ]; then
		SERVICE="-f ${wwan}_SERVICE_GREEN"
	else
		SERVICE="-O ${wwan}_SERVICE_GREEN"
	fi
}

get_modem_information() {
	modem_name=$1
	modem_idx="$(modem port=modem/${modem_name} idx)"

	# Note that it can happen that although the port is present in runt,
	# nothing else (e.g. signal) relating to the modem is.
	if [ -n "$modem_idx" ]; then
		state="$(runt get mm.modem.$modem_idx.status.state)"
		if [ -n "$state" ]; then
			STATE="$state"
		fi

		bars="$(runt get mm.modem.$modem_idx.status.bars)"
		if [ -n "$bars" ]; then
			BARS="$bars"
		fi

		tech="$(runt get mm.modem.$modem_idx.status.gtech)"
		if [ -n "$tech" ]; then
			TECHNOLOGY="$tech"
		fi

		return
	fi
}

name_idx=1
for wwan in $WWAN_LEDS; do
	# Assign default modem states as the associated modem information may
	# not be available.
	STATE=disabled
	TECHNOLOGY=""
	BARS=0

	# Adjust the values if information is available from the associated modem.
	modem_name=$(echo ${MODEM_NAMES} | awk -v N=$name_idx '{print $N}')
	get_modem_information "$modem_name"

	MODEM_STATUS=$(runt get mm.persist.port.$modem_name.status)

	if [ "$MODEM_STATUS" = "updating" ]; then
		SERVICE="-O ${wwan}_SERVICE_GREEN -f ${wwan}_SERVICE_YELLOW"
		SIGNAL="-O ${wwan}_SIGNAL_GREEN -f ${wwan}_SIGNAL_YELLOW"
	elif [ "$MODEM_STATUS" = "recovering" ]; then
		SERVICE="-O ${wwan}_SERVICE_YELLOW -f ${wwan}_SERVICE_GREEN"
		SIGNAL="-O ${wwan}_SIGNAL_YELLOW -f ${wwan}_SIGNAL_GREEN"
	else
		create_signal_led_args "$wwan" "$BARS"
		create_service_led_args "$wwan" "$STATE" "$TECHNOLOGY"
	fi

	eval ledcmd $SERVICE $SIGNAL
	name_idx=$(($name_idx + 1))
done

##############################################################
# GNSS LED
#
# Off: GNSS is disabled
# Flashing: GNSS is enabled but does not have a valid fix
# On: GNSS is enabled and has a valid fix
#
case "$(runt get location.state)" in
    "Enabled, signal") gnss_led_state="-o" ;;
    "Enabled, no signal") gnss_led_state="-f" ;;
    *) gnss_led_state="-O" ;;
esac

ledcmd $gnss_led_state GNSS

##############################################################

exit 0
