#!/bin/sh
#
# Create a complete disk image for the TX64

IMAGE="${1:-${ROOTDIR:-.}/images/image.bin}"
ZIMAGE="${2:-${ROOTDIR:-.}/images/vmlinuz}"
INITRD="${3:-${ROOTDIR:-.}/images/rootfs}"
DISKRAW="${4:-${ROOTDIR:-.}/images/tx64_mfg.img}"

# Disk size in sectors
DISKSECTS="${5:-6000000}"

echo "Making RAW disk..."
# Remove previous file, if any
rm -f "${DISKRAW}"
# Create sparse file
dd if=/dev/zero of="${DISKRAW}" bs=512 count=0 seek=${DISKSECTS}

echo "Run qemu to build image..."
# Boot kernel and run mkffs

qemu-system-x86_64 -net none \
	-nographic \
	$(groups | grep -wq kvm && echo -enable-kvm) \
	-append "root=/dev/ram0 init=/etc/mkffs console=ttyS0" \
	-kernel $ZIMAGE -initrd $INITRD \
	-drive id=diskA,file=$DISKRAW,if=none \
	-device ahci,id=ahci -device ide-drive,drive=diskA,bus=ahci.0 \
	-drive id=diskB,file=$IMAGE,if=none \
	-device ahci,id=ahci1 -device ide-drive,drive=diskB,bus=ahci1.0

echo "Creating bmap..."
bmaptool create "${DISKRAW}" -o "${DISKRAW}.bmap"

exit 0
