#!/bin/sh
#
# TX64 SIM switching utility
# SIM slot control is over AT commands for both LM940 modems.
# No need to reset the modem after changing active slot -- ModemManager will
# detect it from AT#QSS unsolicited messages.

# If named simX, change modem WWANX SIM slot
wwan="${0##*sim}"
idx="$(runt find mm.modem modem.port "modem/wwan$wwan")"
idx="${idx##mm.modem.}"

sim_file="/etc/config/sim$wwan.conf"

case "$1" in
-n)
	echo 2
	;;
-p)
	state=$(pwrctrl -${wwan}) || {
		echo "ERROR: ${state}"
		exit 1
	}
	echo "Current state: ${state##* }"
	;;
-o)
	pwrctrl -${wwan}on || exit 1
	;;
-O)
	pwrctrl -${wwan}off || exit 1
	;;
-m)
	# Built-in modem module is always present
	echo "Cell module detected: yes"
	exit 0
	;;
1|2)
	[ -z "$idx" ] && exit 1
	mmcli -m "$idx" --disable &>/dev/null
	usleep 1000
	mmcli -m "$idx" --command="#SIMDET=$(( $1 - 1 ))" &>/dev/null || exit 1
	echo "$1" > "$sim_file"
	;;
'')
	[ -z "$idx" ] && exit 1
	current="$(mmcli -m "$idx" --command="#SIMDET?" 2>/dev/null | sed -rn 's/^.*: *([0,1]),.*$/\1/p')"
	expected="$(cat "$sim_file" 2>/dev/null)"
	expected="${expected:-1}"
	# The modem always boots with slot 1 active, so it may be out of sync
	# with the .conf when we read it. So re-set it if required.
	if [ "$expected" != "$(( current + 1 ))" ]; then
		mmcli -m "$idx" --disable
		usleep 1000
		mmcli -m "$idx" --command="#SIMDET=$(( expected - 1 ))" &>/dev/null
		echo "$current"
	else
		echo "$expected"
	fi
	;;
*)
	echo "usage: $(basename $0) [none|1|2|-dDnoOp]
Get, set and control WWAN$wwan SIM selection (MM idx $idx)

	-h	help	- this help
	-n	number	- print number of SIM slots
	-o	on	- turn on power to the cell module
	-O	off	- turn off power to the cell module
	-m	module detect	- detect cell module
	-p	power	- report the modem's current power state"
	[ "$1" = -h ] && exit 0 || exit 1
	;;
esac

exit 0

