#!/bin/sh

#
# mkffs -- make flash filesystem for Digi/TX54 NAND
#
# Create and partition a UBI flash region in "User" nand flash.
#

MTDEVICE=/dev/mtd8
UBINUM=0
UBIDEVICE=/dev/ubi0

#
# Make sure ubi is not attached.
#
ubidetach -d $UBINUM > /dev/null

#
# Creat and attach the single large UBI region.
#
ubiformat -y $MTDEVICE
ubiattach -p $MTDEVICE -d $UBINUM

#
# Create the filesystem partitions we want.
#
ubimkvol $UBIDEVICE -N UserFS -m

exit 0
